In [13]:
!uv add python-dotenv spotipy

Resolved 43 packages in 24ms
Checked 39 packages in 9ms

In [16]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import os
from dotenv import load_dotenv

load_dotenv()

True

In [8]:
client_credentials_manager = SpotifyClientCredentials(client_id=os.getenv("SPOTIFY_CLIENT_ID"),
    client_secret=os.getenv("SPOTIFY_CLIENT_SECRET"))

In [9]:
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

In [18]:
playlist_link = "https://open.spotify.com/playlist/37i9dQZEVXbNG2KDcFcKOF?si=1333723a6eff4b7f&nd=1&dlsi=1586c2ede2dc4823"

In [19]:
playlist_URI = playlist_link.split("/")[-1].split("?")[0]
playlist_URI

'37i9dQZEVXbNG2KDcFcKOF'

In [12]:
#extrac data that stored in JSON file
data = sp.playlist_tracks(playlist_URI)
data

HTTP Error for GET to https://api.spotify.com/v1/playlists/37i9dQZEVXbNG2KDcFcKOF/items with Params: {'limit': 50, 'offset': 0, 'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to Active premium subscription required for the owner of the app. When the subscription status changes, it can take a few hours before requests are allowed again.

SpotifyException: http status: 403, code: -1 - https://api.spotify.com/v1/playlists/37i9dQZEVXbNG2KDcFcKOF/items?limit=50&offset=0&additional_types=track:
 Active premium subscription required for the owner of the app. When the subscription status changes, it can take a few hours before requests are allowed again., reason: None

In [13]:
#this dataset contains info about 50 songs (tracks), the info I need stored in 'item'
len(data['items'])

50

In [14]:
# Let's check the first track:
data['items'][0]

{'added_at': '2024-01-26T16:09:07Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/'},
  'href': 'https://api.spotify.com/v1/users/',
  'id': '',
  'type': 'user',
  'uri': 'spotify:user:'},
 'is_local': False,
 'primary_color': None,
 'track': {'album': {'album_type': 'single',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Me35AWHCGqW4sZ7bWWJt1'},
     'href': 'https://api.spotify.com/v1/artists/3Me35AWHCGqW4sZ7bWWJt1',
     'id': '3Me35AWHCGqW4sZ7bWWJt1',
     'name': 'Xavi',
     'type': 'artist',
     'uri': 'spotify:artist:3Me35AWHCGqW4sZ7bWWJt1'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/2IoSjweCu07y9mv5H1Cj3v'},
   'href': 'https://api.spotify.com/v1/albums/2IoSjweCu07y9mv5H1Cj3v',
   'id': '2IoSjweCu07y9mv5H1Cj3v',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b2731501c770de50a22b25d67611',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e021501c770de50a22b25d67611',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d000048511501c770de50a22b25d67611',
     'width': 64}],
   'name': 'La Diabla',
   'release_date': '2023-11-30',
   'release_date_precision': 'day',
   'total_tracks': 1,
   'type': 'album',
   'uri': 'spotify:album:2IoSjweCu07y9mv5H1Cj3v'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Me35AWHCGqW4sZ7bWWJt1'},
    'href': 'https://api.spotify.com/v1/artists/3Me35AWHCGqW4sZ7bWWJt1',
    'id': '3Me35AWHCGqW4sZ7bWWJt1',
    'name': 'Xavi',
    'type': 'artist',
    'uri': 'spotify:artist:3Me35AWHCGqW4sZ7bWWJt1'}],
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'BY',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'BF',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BN',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'NP',
   'RW',
   'TG',
   'UZ',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'disc_number': 1,
  'duration_ms': 172264,
  'episode': False,
  'explicit': False,
  'external_ids': {'isrc': 'USA2P2357356'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/0R6NfOiLzLj4O5VbYSJAjf'},
  'href': 'https://api.spotify.com/v1/tracks/0R6NfOiLzLj4O5VbYSJAjf',
  'id': '0R6NfOiLzLj4O5VbYSJAjf',
  'is_local': False,
  'name': 'La Diabla',
  'popularity': 99,
  'preview_url': 'https://p.scdn.co/mp3-preview/f3eeae4ae180d55cd3c83c4e4c1d657b46aa107e?cid=cd950945d103464faa9ec2c5a8b9f8f3',
  'track': True,
  'track_number': 1,
  'type': 'track',
  'uri': 'spotify:track:0R6NfOiLzLj4O5VbYSJAjf'},
 'video_thumbnail': {'url': None}}

### Parse JSON to get structured data of albumsm

In [17]:
data['items'][0]['track']['album']['id']  #album_id

'2IoSjweCu07y9mv5H1Cj3v'

In [18]:
data['items'][0]['track']['album']['name'] #album name

'La Diabla'

In [19]:
data['items'][0]['track']['album']['release_date'] #release date

'2023-11-30'

In [20]:
data['items'][0]['track']['album']['total_tracks'] #total tracks

1

In [21]:
data['items'][0]['track']['album']['external_urls']['spotify'] #album_url

'https://open.spotify.com/album/2IoSjweCu07y9mv5H1Cj3v'

In [22]:
#structure the data for Album
album_list = []
for row in data['items']:
    album_id = row['track']['album']['id']
    album_name = row['track']['album']['name']
    album_release_date = row['track']['album']['release_date']
    album_total_tracks = row['track']['album']['total_tracks']
    album_url = row['track']['album']['external_urls']['spotify']
    album_element = {'album_id' : album_id,
                    'name' : album_name,
                    'release_date' : album_release_date,
                    'total_tracks' : album_total_tracks,
                    'url' : album_url}
    album_list.append(album_element)

In [23]:
album_list

[{'album_id': '2IoSjweCu07y9mv5H1Cj3v',
  'name': 'La Diabla',
  'release_date': '2023-11-30',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2IoSjweCu07y9mv5H1Cj3v'},
 {'album_id': '2B9amdrHDIKOoEiPUfZGtb',
  'name': 'yes, and?',
  'release_date': '2024-01-12',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2B9amdrHDIKOoEiPUfZGtb'},
 {'album_id': '3UOV8XvCwMKaATRNXrYCjN',
  'name': 'greedy',
  'release_date': '2023-09-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3UOV8XvCwMKaATRNXrYCjN'},
 {'album_id': '6VCO0fDBGbRW8mCEvV95af',
  'name': 'Lovin On Me',
  'release_date': '2023-11-10',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6VCO0fDBGbRW8mCEvV95af'},
 {'album_id': '7tzVd1fwkxsorytCBjEJkU',
  'name': 'The Idol Episode 4 (Music from the HBO Original Series)',
  'release_date': '2023-06-23',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/7tzVd1fwkxsorytCBjEJkU'},
 {'album_id': '2Cn1d2KgbkAqbZCJ1RzdkA',
  'name': 'The Land Is Inhospitable and So Are We',
  'release_date': '2023-09-15',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/2Cn1d2KgbkAqbZCJ1RzdkA'},
 {'album_id': '1NAmidJlEaVgA3MpcPFYGq',
  'name': 'Lover',
  'release_date': '2019-08-23',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/1NAmidJlEaVgA3MpcPFYGq'},
 {'album_id': '50ZenUP4O2Q5eCy2NRNvuz',
  'name': 'Stick Season',
  'release_date': '2022-10-14',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/50ZenUP4O2Q5eCy2NRNvuz'},
 {'album_id': '2RRYaYHY7fIIdvFlvgb5vq',
  'name': 'american dream',
  'release_date': '2024-01-12',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/2RRYaYHY7fIIdvFlvgb5vq'},
 {'album_id': '0lgs2Sa82lyX89nBUWyUy6',
  'name': 'FERXXOCALIPSIS',
  'release_date': '2023-12-01',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/0lgs2Sa82lyX89nBUWyUy6'},
 {'album_id': '5U20AVSsUvycGtWip4XQfo',
  'name': 'ORQUÍDEAS',
  'release_date': '2024-01-12',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/5U20AVSsUvycGtWip4XQfo'},
 {'album_id': '30KJEN3ICjhYsZ1NgunRCr',
  'name': 'La Víctima',
  'release_date': '2023-08-17',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/30KJEN3ICjhYsZ1NgunRCr'},
 {'album_id': '68ishLKwqH5oH79kUteEHG',
  'name': 'Read My Lips',
  'release_date': '2002-06-06',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/68ishLKwqH5oH79kUteEHG'},
 {'album_id': '5O0zUvdnJr0RbWzLFneN2i',
  'name': 'Popular (Music from the HBO Original Series)',
  'release_date': '2023-06-02',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/5O0zUvdnJr0RbWzLFneN2i'},
 {'album_id': '0HMTQPl6rJmP7sQEaRYHRo',
  'name': 'Young Miko: Bzrp Music Sessions, Vol. 58',
  'release_date': '2024-01-10',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0HMTQPl6rJmP7sQEaRYHRo'},
 {'album_id': '3VLY9g3CAG1Y5r2eGVEaZ0',
  'name': 'BELLAKEO',
  'release_date': '2023-12-07',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3VLY9g3CAG1Y5r2eGVEaZ0'},
 {'album_id': '7nacKlk586eLRBSIsrk9DB',
  'name': "I've Tried Everything But Therapy (Part 1)",
  'release_date': '2023-09-15',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/7nacKlk586eLRBSIsrk9DB'},
 {'album_id': '78bpIziExqiI9qztvNFlQu',
  'name': 'AM',
  'release_date': '2013-09-09',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/78bpIziExqiI9qztvNFlQu'},
 {'album_id': '4FftCsAcXXD1nFO9RFUNFO',
  'name': 'nadie sabe lo que va a pasar mañana',
  'release_date': '2023-10-13',
  'total_tracks': 22,
  'url': 'https://open.spotify.com/album/4FftCsAcXXD1nFO9RFUNFO'},
 {'album_id': '18ogtNq9F7DmMkNYO6Xb4k',
  'name': 'Strangers',
  'release_date': '2023-09-01',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/18ogtNq9F7DmMkNYO6Xb4k'},
 {'album_id': '1bBez9PNvkJPW08bU7NYta',
  'name': 'Scarlet',
  'release_date': '2023-09-20',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/1bBez9PNvkJPW08bU7NYta'},
 {'album_id': '5pSk3c3wVwnb2arb6ohCPU',
  'name': 'GOLDEN',
  'release_date': '2023-11-03',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/5pSk3c3wVwnb2arb6ohCPU'},
 {'album_id': '0FqAaUEyKCyUNFE1uQPZ7i',
  'name': 'MAÑANA SERÁ BONITO (BICHOTA SEASON)',
  'release_date': '2023-08-10',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/0FqAaUEyKCyUNFE1uQPZ7i'},
 {'album_id': '29aSKB1qPEbN0Qf9OPSQpw',
  'name': 'Beautiful Things',
  'release_date': '2024-01-18',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/29aSKB1qPEbN0Qf9OPSQpw'},
 {'album_id': '22sXXkKgjEuawIFL1e1tRw',
  'name': 'Water',
  'release_date': '2023-07-28',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/22sXXkKgjEuawIFL1e1tRw'},
 {'album_id': '2ODvWsOgouMbaA5xf0RkJe',
  'name': 'Starboy',
  'release_date': '2016-11-25',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/2ODvWsOgouMbaA5xf0RkJe'},
 {'album_id': '5pTaRVLwZOFObIbRBubmeb',
  'name': 'Houdini',
  'release_date': '2023-11-09',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/5pTaRVLwZOFObIbRBubmeb'},
 {'album_id': '4x6cjOcVz44aiLSOHCLKPd',
  'name': 'Que Onda',
  'release_date': '2023-08-30',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4x6cjOcVz44aiLSOHCLKPd'},
 {'album_id': '1xJHno7SmdVtZAtXbdbDZp',
  'name': 'GUTS',
  'release_date': '2023-09-08',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/1xJHno7SmdVtZAtXbdbDZp'},
 {'album_id': '3AafSrFIbJPH6BJHiJm1Cd',
  'name': 'What Was I Made For? [From The Motion Picture "Barbie"]',
  'release_date': '2023-07-13',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3AafSrFIbJPH6BJHiJm1Cd'},
 {'album_id': '3yoNZlqerJnsnMN5EDwwBS',
  'name': 'Strange Trails',
  'release_date': '2015-04-07',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/3yoNZlqerJnsnMN5EDwwBS'},
 {'album_id': '5pSk3c3wVwnb2arb6ohCPU',
  'name': 'GOLDEN',
  'release_date': '2023-11-03',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/5pSk3c3wVwnb2arb6ohCPU'},
 {'album_id': '5S9b8euumqMhQbMk0zzQdH',
  'name': 'Dream Your Life Away (Special Edition)',
  'release_date': '2014-09-09',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/5S9b8euumqMhQbMk0zzQdH'},
 {'album_id': '2g4aJTa5ejGpp0O0GKzWAQ',
  'name': 'emails i can’t send fwd:',
  'release_date': '2023-03-17',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/2g4aJTa5ejGpp0O0GKzWAQ'},
 {'album_id': '66k6EGkPtYoN44anGIsEPW',
  'name': 'Si No Estás',
  'release_date': '2022-09-23',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/66k6EGkPtYoN44anGIsEPW'},
 {'album_id': '5r36AJ6VOJtp00oxSkBZ5h',
  'name': "Harry's House",
  'release_date': '2022-05-20',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/5r36AJ6VOJtp00oxSkBZ5h'},
 {'album_id': '4K5YnziH8o3NoEsxv8zviL',
  'name': 'Never Lose Me',
  'release_date': '2023-11-30',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4K5YnziH8o3NoEsxv8zviL'},
 {'album_id': '4rJDCELWL0fjdmN9Gn4f4g',
  'name': 'The Forever Story (Extended Version)',
  'release_date': '2022-10-31',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/4rJDCELWL0fjdmN9Gn4f4g'},
 {'album_id': '3zu0hJJew2qXZNlselIQk8',
  'name': "Pa las Baby's Y Belikeada",
  'release_date': '2023-10-20',
  'total_tracks': 30,
  'url': 'https://open.spotify.com/album/3zu0hJJew2qXZNlselIQk8'},
 {'album_id': '4czdORdCWP9umpbhFXK2fW',
  'name': 'For All The Dogs',
  'release_date': '2023-10-06',
  'total_tracks': 23,
  'url': 'https://open.spotify.com/album/4czdORdCWP9umpbhFXK2fW'},
 {'album_id': '1bBez9PNvkJPW08bU7NYta',
  'name': 'Scarlet',
  'release_date': '2023-09-20',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/1bBez9PNvkJPW08bU7NYta'},
 {'album_id': '6PbnGueEO6LGodPfvNldYf',
  'name': 'Zach Bryan',
  'release_date': '2023-08-25',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/6PbnGueEO6LGodPfvNldYf'},
 {'album_id': '6NcI39WPu4kY6Tul11nhSv',
  'name': 'Daylight',
  'release_date': '2023-04-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6NcI39WPu4kY6Tul11nhSv'},
 {'album_id': '5MU0RmBSpoSxOPYBfcobDc',
  'name': 'Prada',
  'release_date': '2023-08-11',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/5MU0RmBSpoSxOPYBfcobDc'},
 {'album_id': '6ZG5lRT77aJ3btmArcykra',
  'name': 'Parachutes',
  'release_date': '2000-07-10',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/6ZG5lRT77aJ3btmArcykra'},
 {'album_id': '5cH7FqB7JD5q1tJXJ7FHYu',
  'name': 'Dance The Night (From Barbie The Album)',
  'release_date': '2023-05-25',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/5cH7FqB7JD5q1tJXJ7FHYu'},
 {'album_id': '3Fk8yQvPlCHgwR2pNhEIRA',
  'name': 'Don Juan',
  'release_date': '2023-08-25',
  'total_tracks': 25,
  'url': 'https://open.spotify.com/album/3Fk8yQvPlCHgwR2pNhEIRA'},
 {'album_id': '2RRYaYHY7fIIdvFlvgb5vq',
  'name': 'american dream',
  'release_date': '2024-01-12',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/2RRYaYHY7fIIdvFlvgb5vq'},
 {'album_id': '4AdZV63ycxFLF6Hcol0QnB',
  'name': 'Starboy',
  'release_date': '2016-11-24',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/4AdZV63ycxFLF6Hcol0QnB'},
 {'album_id': '5DvJgsMLbaR1HmAI6VhfcQ',
  'name': 'Endless Summer Vacation',
  'release_date': '2023-08-18',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/5DvJgsMLbaR1HmAI6VhfcQ'}]

Parse JSON to get structured data of artists

In [28]:
#similar to album, I also want to try the second method to extract artist data.
artist_list = []
for row in data['items']:
    for key, value in row.items():
        if key == 'track':
            for artist in value['artists']:
                artist_dict = {'artist_id' : artist['id'],
                'artist_name' : artist['name'],
                'external_url' : artist['href'],
                }
                artist_list.append(artist_dict)

In [29]:
artist_list

[{'artist_id': '3Me35AWHCGqW4sZ7bWWJt1',
  'artist_name': 'Xavi',
  'external_url': 'https://api.spotify.com/v1/artists/3Me35AWHCGqW4sZ7bWWJt1'},
 {'artist_id': '66CXWjxzNUsdJxJ2JdwvnR',
  'artist_name': 'Ariana Grande',
  'external_url': 'https://api.spotify.com/v1/artists/66CXWjxzNUsdJxJ2JdwvnR'},
 {'artist_id': '45dkTj5sMRSjrmBSBeiHym',
  'artist_name': 'Tate McRae',
  'external_url': 'https://api.spotify.com/v1/artists/45dkTj5sMRSjrmBSBeiHym'},
 {'artist_id': '2LIk90788K0zvyj2JJVwkJ',
  'artist_name': 'Jack Harlow',
  'external_url': 'https://api.spotify.com/v1/artists/2LIk90788K0zvyj2JJVwkJ'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '250b0Wlc5Vk0CoUsaCY84M',
  'artist_name': 'JENNIE',
  'external_url': 'https://api.spotify.com/v1/artists/250b0Wlc5Vk0CoUsaCY84M'},
 {'artist_id': '1pBLC0qVRTB5zVMuteQ9jJ',
  'artist_name': 'Lily-Rose Depp',
  'external_url': 'https://api.spotify.com/v1/artists/1pBLC0qVRTB5zVMuteQ9jJ'},
 {'artist_id': '2uYWxilOVlUdk4oV9DvwqK',
  'artist_name': 'Mitski',
  'external_url': 'https://api.spotify.com/v1/artists/2uYWxilOVlUdk4oV9DvwqK'},
 {'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift',
  'external_url': 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02'},
 {'artist_id': '2RQXRUsr4IW1f3mKyKsy4B',
  'artist_name': 'Noah Kahan',
  'external_url': 'https://api.spotify.com/v1/artists/2RQXRUsr4IW1f3mKyKsy4B'},
 {'artist_id': '1URnnhqYAYcrqrcwql10ft',
  'artist_name': '21 Savage',
  'external_url': 'https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft'},
 {'artist_id': '2LRoIwlKmHjgvigdNGBHNo',
  'artist_name': 'Feid',
  'external_url': 'https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo'},
 {'artist_id': '7jAs1uPnpfNmT6e5qtEPxq',
  'artist_name': 'ATL Jacob',
  'external_url': 'https://api.spotify.com/v1/artists/7jAs1uPnpfNmT6e5qtEPxq'},
 {'artist_id': '1U1el3k54VvEUzo3ybLPlM',
  'artist_name': 'Kali Uchis',
  'external_url': 'https://api.spotify.com/v1/artists/1U1el3k54VvEUzo3ybLPlM'},
 {'artist_id': '12GqGscKJx3aE4t07u7eVZ',
  'artist_name': 'Peso Pluma',
  'external_url': 'https://api.spotify.com/v1/artists/12GqGscKJx3aE4t07u7eVZ'},
 {'artist_id': '3Me35AWHCGqW4sZ7bWWJt1',
  'artist_name': 'Xavi',
  'external_url': 'https://api.spotify.com/v1/artists/3Me35AWHCGqW4sZ7bWWJt1'},
 {'artist_id': '2cBh5lVMg222FFuRU7EfDE',
  'artist_name': 'Sophie Ellis-Bextor',
  'external_url': 'https://api.spotify.com/v1/artists/2cBh5lVMg222FFuRU7EfDE'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '699OTQXzgjhIYAHMy9RyPD',
  'artist_name': 'Playboi Carti',
  'external_url': 'https://api.spotify.com/v1/artists/699OTQXzgjhIYAHMy9RyPD'},
 {'artist_id': '6tbjWDEIzxoDsBA1FuhfPW',
  'artist_name': 'Madonna',
  'external_url': 'https://api.spotify.com/v1/artists/6tbjWDEIzxoDsBA1FuhfPW'},
 {'artist_id': '716NhGYqD1jl2wI1Qkgq36',
  'artist_name': 'Bizarrap',
  'external_url': 'https://api.spotify.com/v1/artists/716NhGYqD1jl2wI1Qkgq36'},
 {'artist_id': '3qsKSpcV3ncke3hw52JSMB',
  'artist_name': 'Young Miko',
  'external_url': 'https://api.spotify.com/v1/artists/3qsKSpcV3ncke3hw52JSMB'},
 {'artist_id': '12GqGscKJx3aE4t07u7eVZ',
  'artist_name': 'Peso Pluma',
  'external_url': 'https://api.spotify.com/v1/artists/12GqGscKJx3aE4t07u7eVZ'},
 {'artist_id': '7FNnA9vBm6EKceENgCGRMb',
  'artist_name': 'Anitta',
  'external_url': 'https://api.spotify.com/v1/artists/7FNnA9vBm6EKceENgCGRMb'},
 {'artist_id': '33qOK5uJ8AR2xuQQAhHump',
  'artist_name': 'Teddy Swims',
  'external_url': 'https://api.spotify.com/v1/artists/33qOK5uJ8AR2xuQQAhHump'},
 {'artist_id': '7Ln80lUS6He07XvHI8qqHH',
  'artist_name': 'Arctic Monkeys',
  'external_url': 'https://api.spotify.com/v1/artists/7Ln80lUS6He07XvHI8qqHH'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '2LRoIwlKmHjgvigdNGBHNo',
  'artist_name': 'Feid',
  'external_url': 'https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo'},
 {'artist_id': '7uMDnSZyUYNBPLhPMNuaM2',
  'artist_name': 'Kenya Grace',
  'external_url': 'https://api.spotify.com/v1/artists/7uMDnSZyUYNBPLhPMNuaM2'},
 {'artist_id': '5cj0lLjcoR7YOSnhnX0Po5',
  'artist_name': 'Doja Cat',
  'external_url': 'https://api.spotify.com/v1/artists/5cj0lLjcoR7YOSnhnX0Po5'},
 {'artist_id': '6HaGTQPmzraVmaVxvz6EUc',
  'artist_name': 'Jung Kook',
  'external_url': 'https://api.spotify.com/v1/artists/6HaGTQPmzraVmaVxvz6EUc'},
 {'artist_id': '3MdXrJWsbVzdn6fe5JYkSQ',
  'artist_name': 'Latto',
  'external_url': 'https://api.spotify.com/v1/artists/3MdXrJWsbVzdn6fe5JYkSQ'},
 {'artist_id': '790FomKkXshlbRYZFtlgla',
  'artist_name': 'KAROL G',
  'external_url': 'https://api.spotify.com/v1/artists/790FomKkXshlbRYZFtlgla'},
 {'artist_id': '12GqGscKJx3aE4t07u7eVZ',
  'artist_name': 'Peso Pluma',
  'external_url': 'https://api.spotify.com/v1/artists/12GqGscKJx3aE4t07u7eVZ'},
 {'artist_id': '22wbnEMDvgVIAGdFeek6ET',
  'artist_name': 'Benson Boone',
  'external_url': 'https://api.spotify.com/v1/artists/22wbnEMDvgVIAGdFeek6ET'},
 {'artist_id': '3SozjO3Lat463tQICI9LcE',
  'artist_name': 'Tyla',
  'external_url': 'https://api.spotify.com/v1/artists/3SozjO3Lat463tQICI9LcE'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '4tZwfgrHOc3mvqYlEYSvVi',
  'artist_name': 'Daft Punk',
  'external_url': 'https://api.spotify.com/v1/artists/4tZwfgrHOc3mvqYlEYSvVi'},
 {'artist_id': '6M2wZ9GZgrQXHCFfjv46we',
  'artist_name': 'Dua Lipa',
  'external_url': 'https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we'},
 {'artist_id': '6dLuQ5qXxIuWc5urxfIiZR',
  'artist_name': 'Calle 24',
  'external_url': 'https://api.spotify.com/v1/artists/6dLuQ5qXxIuWc5urxfIiZR'},
 {'artist_id': '2rmkQLzj0k4nZdQehOUByO',
  'artist_name': 'Chino Pacas',
  'external_url': 'https://api.spotify.com/v1/artists/2rmkQLzj0k4nZdQehOUByO'},
 {'artist_id': '0ys2OFYzWYB5hRDLCsBqxt',
  'artist_name': 'Fuerza Regida',
  'external_url': 'https://api.spotify.com/v1/artists/0ys2OFYzWYB5hRDLCsBqxt'},
 {'artist_id': '1McMsnEElThX1knmY4oliG',
  'artist_name': 'Olivia Rodrigo',
  'external_url': 'https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG'},
 {'artist_id': '6qqNVTkY8uBg9cP3Jd7DAH',
  'artist_name': 'Billie Eilish',
  'external_url': 'https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH'},
 {'artist_id': '6ltzsmQQbmdoHHbLZ4ZN25',
  'artist_name': 'Lord Huron',
  'external_url': 'https://api.spotify.com/v1/artists/6ltzsmQQbmdoHHbLZ4ZN25'},
 {'artist_id': '6HaGTQPmzraVmaVxvz6EUc',
  'artist_name': 'Jung Kook',
  'external_url': 'https://api.spotify.com/v1/artists/6HaGTQPmzraVmaVxvz6EUc'},
 {'artist_id': '10exVja0key0uqUkk6LJRT',
  'artist_name': 'Vance Joy',
  'external_url': 'https://api.spotify.com/v1/artists/10exVja0key0uqUkk6LJRT'},
 {'artist_id': '74KM79TiuVKeVCqs8QtB0B',
  'artist_name': 'Sabrina Carpenter',
  'external_url': 'https://api.spotify.com/v1/artists/74KM79TiuVKeVCqs8QtB0B'},
 {'artist_id': '0jbo7KFNMiIkfBR6ih0yhm',
  'artist_name': 'iñigo quintero',
  'external_url': 'https://api.spotify.com/v1/artists/0jbo7KFNMiIkfBR6ih0yhm'},
 {'artist_id': '6KImCVD70vtIoJWnq6nGn3',
  'artist_name': 'Harry Styles',
  'external_url': 'https://api.spotify.com/v1/artists/6KImCVD70vtIoJWnq6nGn3'},
 {'artist_id': '08PvCOlef4xdOr20jFSTPd',
  'artist_name': 'Flo Milli',
  'external_url': 'https://api.spotify.com/v1/artists/08PvCOlef4xdOr20jFSTPd'},
 {'artist_id': '6U3ybJ9UHNKEdsH7ktGBZ7',
  'artist_name': 'JID',
  'external_url': 'https://api.spotify.com/v1/artists/6U3ybJ9UHNKEdsH7ktGBZ7'},
 {'artist_id': '1URnnhqYAYcrqrcwql10ft',
  'artist_name': '21 Savage',
  'external_url': 'https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft'},
 {'artist_id': '3IJ21966TwNZI24MwZHMu4',
  'artist_name': 'Baby Tate',
  'external_url': 'https://api.spotify.com/v1/artists/3IJ21966TwNZI24MwZHMu4'},
 {'artist_id': '0ys2OFYzWYB5hRDLCsBqxt',
  'artist_name': 'Fuerza Regida',
  'external_url': 'https://api.spotify.com/v1/artists/0ys2OFYzWYB5hRDLCsBqxt'},
 {'artist_id': '64KEffDW9EtZ1y2vBYgq8T',
  'artist_name': 'Marshmello',
  'external_url': 'https://api.spotify.com/v1/artists/64KEffDW9EtZ1y2vBYgq8T'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '3DbwFQlvLxRSi2uX8mf81A',
  'artist_name': 'Sexyy Red',
  'external_url': 'https://api.spotify.com/v1/artists/3DbwFQlvLxRSi2uX8mf81A'},
 {'artist_id': '7tYKF4w9nC0nq9CsPZTHyP',
  'artist_name': 'SZA',
  'external_url': 'https://api.spotify.com/v1/artists/7tYKF4w9nC0nq9CsPZTHyP'},
 {'artist_id': '5cj0lLjcoR7YOSnhnX0Po5',
  'artist_name': 'Doja Cat',
  'external_url': 'https://api.spotify.com/v1/artists/5cj0lLjcoR7YOSnhnX0Po5'},
 {'artist_id': '40ZNYROS4zLfyyBSs2PGe2',
  'artist_name': 'Zach Bryan',
  'external_url': 'https://api.spotify.com/v1/artists/40ZNYROS4zLfyyBSs2PGe2'},
 {'artist_id': '70kkdajctXSbqSMJbQO424',
  'artist_name': 'Kacey Musgraves',
  'external_url': 'https://api.spotify.com/v1/artists/70kkdajctXSbqSMJbQO424'},
 {'artist_id': '33NVpKoXjItPwUJTMZIOiY',
  'artist_name': 'David Kushner',
  'external_url': 'https://api.spotify.com/v1/artists/33NVpKoXjItPwUJTMZIOiY'},
 {'artist_id': '5wCmhq5J2hPwL2r0eKurxn',
  'artist_name': 'cassö',
  'external_url': 'https://api.spotify.com/v1/artists/5wCmhq5J2hPwL2r0eKurxn'},
 {'artist_id': '5KKpBU5eC2tJDzf0wmlRp2',
  'artist_name': 'RAYE',
  'external_url': 'https://api.spotify.com/v1/artists/5KKpBU5eC2tJDzf0wmlRp2'},
 {'artist_id': '5VadK1havLhK1OpKYsXv9y',
  'artist_name': 'D-Block Europe',
  'external_url': 'https://api.spotify.com/v1/artists/5VadK1havLhK1OpKYsXv9y'},
 {'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay',
  'external_url': 'https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU'},
 {'artist_id': '6M2wZ9GZgrQXHCFfjv46we',
  'artist_name': 'Dua Lipa',
  'external_url': 'https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we'},
 {'artist_id': '1r4hJ1h58CWwUQe3MxPuau',
  'artist_name': 'Maluma',
  'external_url': 'https://api.spotify.com/v1/artists/1r4hJ1h58CWwUQe3MxPuau'},
 {'artist_id': '66ihevNkSYNzRAl44dx6jJ',
  'artist_name': 'Carin Leon',
  'external_url': 'https://api.spotify.com/v1/artists/66ihevNkSYNzRAl44dx6jJ'},
 {'artist_id': '1URnnhqYAYcrqrcwql10ft',
  'artist_name': '21 Savage',
  'external_url': 'https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft'},
 {'artist_id': '0Y5tJX1MQlPlqiwlOH1tJY',
  'artist_name': 'Travis Scott',
  'external_url': 'https://api.spotify.com/v1/artists/0Y5tJX1MQlPlqiwlOH1tJY'},
 {'artist_id': '0iEtIxbK0KxaSlF7G42ZOp',
  'artist_name': 'Metro Boomin',
  'external_url': 'https://api.spotify.com/v1/artists/0iEtIxbK0KxaSlF7G42ZOp'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '5YGY8feqx7naU7z4HrwZM6',
  'artist_name': 'Miley Cyrus',
  'external_url': 'https://api.spotify.com/v1/artists/5YGY8feqx7naU7z4HrwZM6'}]

### Parse JSON to get structured data of songs

In [30]:
song_list = []
for row in data['items']:
    song_id = row['track']['id']
    song_name = row['track']['name']
    song_duration = row['track']['duration_ms']
    song_url = row['track']['external_urls']['spotify']
    song_popularity = row['track']['popularity']
    song_added = row['added_at']
    album_id = row['track']['album']['id']
    artist_id = row['track']['album']['artists'][0]['id']
    song_element = {'song_id':song_id,'song_name':song_name,'duration_ms':song_duration,'url':song_url,
                    'popularity':song_popularity,'song_added':song_added,'album_id':album_id,
                    'artist_id':artist_id
                   }
    song_list.append(song_element)

In [31]:
song_list

[{'song_id': '0R6NfOiLzLj4O5VbYSJAjf',
  'song_name': 'La Diabla',
  'duration_ms': 172264,
  'url': 'https://open.spotify.com/track/0R6NfOiLzLj4O5VbYSJAjf',
  'popularity': 99,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '2IoSjweCu07y9mv5H1Cj3v',
  'artist_id': '3Me35AWHCGqW4sZ7bWWJt1'},
 {'song_id': '7gaA3wERFkFkgivjwbSvkG',
  'song_name': 'yes, and?',
  'duration_ms': 214994,
  'url': 'https://open.spotify.com/track/7gaA3wERFkFkgivjwbSvkG',
  'popularity': 97,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '2B9amdrHDIKOoEiPUfZGtb',
  'artist_id': '66CXWjxzNUsdJxJ2JdwvnR'},
 {'song_id': '3rUGC1vUpkDG9CZFHMur1t',
  'song_name': 'greedy',
  'duration_ms': 131872,
  'url': 'https://open.spotify.com/track/3rUGC1vUpkDG9CZFHMur1t',
  'popularity': 100,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '3UOV8XvCwMKaATRNXrYCjN',
  'artist_id': '45dkTj5sMRSjrmBSBeiHym'},
 {'song_id': '4xhsWYTOGcal8zt0J161CU',
  'song_name': 'Lovin On Me',
  'duration_ms': 138411,
  'url': 'https://open.spotify.com/track/4xhsWYTOGcal8zt0J161CU',
  'popularity': 99,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '6VCO0fDBGbRW8mCEvV95af',
  'artist_id': '2LIk90788K0zvyj2JJVwkJ'},
 {'song_id': '7CyPwkp0oE8Ro9Dd5CUDjW',
  'song_name': 'One Of The Girls (with JENNIE, Lily Rose Depp)',
  'duration_ms': 244684,
  'url': 'https://open.spotify.com/track/7CyPwkp0oE8Ro9Dd5CUDjW',
  'popularity': 98,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '7tzVd1fwkxsorytCBjEJkU',
  'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ'},
 {'song_id': '3vkCueOmm7xQDoJ17W1Pm3',
  'song_name': 'My Love Mine All Mine',
  'duration_ms': 137773,
  'url': 'https://open.spotify.com/track/3vkCueOmm7xQDoJ17W1Pm3',
  'popularity': 99,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '2Cn1d2KgbkAqbZCJ1RzdkA',
  'artist_id': '2uYWxilOVlUdk4oV9DvwqK'},
 {'song_id': '1BxfuPKGuaTgP7aM0Bbdwr',
  'song_name': 'Cruel Summer',
  'duration_ms': 178426,
  'url': 'https://open.spotify.com/track/1BxfuPKGuaTgP7aM0Bbdwr',
  'popularity': 99,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '1NAmidJlEaVgA3MpcPFYGq',
  'artist_id': '06HL4z0CvFAxyc27GXpf02'},
 {'song_id': '0mflMxspEfB0VbI1kyLiAv',
  'song_name': 'Stick Season',
  'duration_ms': 182346,
  'url': 'https://open.spotify.com/track/0mflMxspEfB0VbI1kyLiAv',
  'popularity': 97,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '50ZenUP4O2Q5eCy2NRNvuz',
  'artist_id': '2RQXRUsr4IW1f3mKyKsy4B'},
 {'song_id': '52eIcoLUM25zbQupAZYoFh',
  'song_name': 'redrum',
  'duration_ms': 270697,
  'url': 'https://open.spotify.com/track/52eIcoLUM25zbQupAZYoFh',
  'popularity': 95,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '2RRYaYHY7fIIdvFlvgb5vq',
  'artist_id': '1URnnhqYAYcrqrcwql10ft'},
 {'song_id': '7bywjHOc0wSjGGbj04XbVi',
  'song_name': 'LUNA',
  'duration_ms': 196800,
  'url': 'https://open.spotify.com/track/7bywjHOc0wSjGGbj04XbVi',
  'popularity': 97,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '0lgs2Sa82lyX89nBUWyUy6',
  'artist_id': '2LRoIwlKmHjgvigdNGBHNo'},
 {'song_id': '6XaJfhwof7qIgbbXO5tIQI',
  'song_name': 'Igual Que Un Ángel (with Peso Pluma)',
  'duration_ms': 260370,
  'url': 'https://open.spotify.com/track/6XaJfhwof7qIgbbXO5tIQI',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5U20AVSsUvycGtWip4XQfo',
  'artist_id': '1U1el3k54VvEUzo3ybLPlM'},
 {'song_id': '5XVdHRf4CAJ2Jm0uMIy5qY',
  'song_name': 'La Víctima',
  'duration_ms': 156345,
  'url': 'https://open.spotify.com/track/5XVdHRf4CAJ2Jm0uMIy5qY',
  'popularity': 96,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '30KJEN3ICjhYsZ1NgunRCr',
  'artist_id': '3Me35AWHCGqW4sZ7bWWJt1'},
 {'song_id': '4tKGFmENO69tZR9ahgZu48',
  'song_name': 'Murder On The Dancefloor',
  'duration_ms': 230013,
  'url': 'https://open.spotify.com/track/4tKGFmENO69tZR9ahgZu48',
  'popularity': 93,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '68ishLKwqH5oH79kUteEHG',
  'artist_id': '2cBh5lVMg222FFuRU7EfDE'},
 {'song_id': '6WzRpISELf3YglGAh7TXcG',
  'song_name': 'Popular (with Playboi Carti & Madonna) - From The Idol Vol. 1 (Music from the HBO Original Series)',
  'duration_ms': 215466,
  'url': 'https://open.spotify.com/track/6WzRpISELf3YglGAh7TXcG',
  'popularity': 96,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5O0zUvdnJr0RbWzLFneN2i',
  'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ'},
 {'song_id': '6VciS3dRMpZhJiDxT8ArFi',
  'song_name': 'Young Miko: Bzrp Music Sessions, Vol. 58',
  'duration_ms': 187172,
  'url': 'https://open.spotify.com/track/6VciS3dRMpZhJiDxT8ArFi',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '0HMTQPl6rJmP7sQEaRYHRo',
  'artist_id': '716NhGYqD1jl2wI1Qkgq36'},
 {'song_id': '05WVKTdZhlIMX4qqMLuo0f',
  'song_name': 'BELLAKEO',
  'duration_ms': 197333,
  'url': 'https://open.spotify.com/track/05WVKTdZhlIMX4qqMLuo0f',
  'popularity': 95,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '3VLY9g3CAG1Y5r2eGVEaZ0',
  'artist_id': '12GqGscKJx3aE4t07u7eVZ'},
 {'song_id': '17phhZDn6oGtzMe56NuWvj',
  'song_name': 'Lose Control',
  'duration_ms': 210688,
  'url': 'https://open.spotify.com/track/17phhZDn6oGtzMe56NuWvj',
  'popularity': 91,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '7nacKlk586eLRBSIsrk9DB',
  'artist_id': '33qOK5uJ8AR2xuQQAhHump'},
 {'song_id': '5XeFesFbtLpXzIVDNQP22n',
  'song_name': 'I Wanna Be Yours',
  'duration_ms': 183956,
  'url': 'https://open.spotify.com/track/5XeFesFbtLpXzIVDNQP22n',
  'popularity': 96,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '78bpIziExqiI9qztvNFlQu',
  'artist_id': '7Ln80lUS6He07XvHI8qqHH'},
 {'song_id': '7iQXYTyuG13aoeHxGG28Nh',
  'song_name': 'PERRO NEGRO',
  'duration_ms': 162767,
  'url': 'https://open.spotify.com/track/7iQXYTyuG13aoeHxGG28Nh',
  'popularity': 96,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '4FftCsAcXXD1nFO9RFUNFO',
  'artist_id': '4q3ewBCX7sLwd24euuV69X'},
 {'song_id': '5mjYQaktjmjcMKcUIcqz4s',
  'song_name': 'Strangers',
  'duration_ms': 172964,
  'url': 'https://open.spotify.com/track/5mjYQaktjmjcMKcUIcqz4s',
  'popularity': 96,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '18ogtNq9F7DmMkNYO6Xb4k',
  'artist_id': '7uMDnSZyUYNBPLhPMNuaM2'},
 {'song_id': '56y1jOTK0XSvJzVv9vHQBK',
  'song_name': 'Paint The Town Red',
  'duration_ms': 230480,
  'url': 'https://open.spotify.com/track/56y1jOTK0XSvJzVv9vHQBK',
  'popularity': 88,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '1bBez9PNvkJPW08bU7NYta',
  'artist_id': '5cj0lLjcoR7YOSnhnX0Po5'},
 {'song_id': '2HRgqmZQC0MC7GeNuDIXHN',
  'song_name': 'Seven (feat. Latto) (Explicit Ver.)',
  'duration_ms': 183550,
  'url': 'https://open.spotify.com/track/2HRgqmZQC0MC7GeNuDIXHN',
  'popularity': 90,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5pSk3c3wVwnb2arb6ohCPU',
  'artist_id': '6HaGTQPmzraVmaVxvz6EUc'},
 {'song_id': '5RqSsdzTNPX1uzkmlHCFvK',
  'song_name': 'QLONA',
  'duration_ms': 172797,
  'url': 'https://open.spotify.com/track/5RqSsdzTNPX1uzkmlHCFvK',
  'popularity': 93,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '0FqAaUEyKCyUNFE1uQPZ7i',
  'artist_id': '790FomKkXshlbRYZFtlgla'},
 {'song_id': '6tNQ70jh4OwmPGpYy6R2o9',
  'song_name': 'Beautiful Things',
  'duration_ms': 180304,
  'url': 'https://open.spotify.com/track/6tNQ70jh4OwmPGpYy6R2o9',
  'popularity': 91,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '29aSKB1qPEbN0Qf9OPSQpw',
  'artist_id': '22wbnEMDvgVIAGdFeek6ET'},
 {'song_id': '5aIVCx5tnk0ntmdiinnYvw',
  'song_name': 'Water',
  'duration_ms': 200255,
  'url': 'https://open.spotify.com/track/5aIVCx5tnk0ntmdiinnYvw',
  'popularity': 95,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '22sXXkKgjEuawIFL1e1tRw',
  'artist_id': '3SozjO3Lat463tQICI9LcE'},
 {'song_id': '7MXVkk9YMctZqd1Srtv4MB',
  'song_name': 'Starboy',
  'duration_ms': 230453,
  'url': 'https://open.spotify.com/track/7MXVkk9YMctZqd1Srtv4MB',
  'popularity': 95,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '2ODvWsOgouMbaA5xf0RkJe',
  'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ'},
 {'song_id': '4OMJGnvZfDvsePyCwRGO7X',
  'song_name': 'Houdini',
  'duration_ms': 185917,
  'url': 'https://open.spotify.com/track/4OMJGnvZfDvsePyCwRGO7X',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5pTaRVLwZOFObIbRBubmeb',
  'artist_id': '6M2wZ9GZgrQXHCFfjv46we'},
 {'song_id': '6uIIdjYTxxpWOyWuVXrKQO',
  'song_name': 'Que Onda',
  'duration_ms': 191466,
  'url': 'https://open.spotify.com/track/6uIIdjYTxxpWOyWuVXrKQO',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '4x6cjOcVz44aiLSOHCLKPd',
  'artist_id': '6dLuQ5qXxIuWc5urxfIiZR'},
 {'song_id': '1kuGVB7EU95pJObxwvfwKS',
  'song_name': 'vampire',
  'duration_ms': 219724,
  'url': 'https://open.spotify.com/track/1kuGVB7EU95pJObxwvfwKS',
  'popularity': 95,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '1xJHno7SmdVtZAtXbdbDZp',
  'artist_id': '1McMsnEElThX1knmY4oliG'},
 {'song_id': '6wf7Yu7cxBSPrRlWeSeK0Q',
  'song_name': 'What Was I Made For? [From The Motion Picture "Barbie"]',
  'duration_ms': 222369,
  'url': 'https://open.spotify.com/track/6wf7Yu7cxBSPrRlWeSeK0Q',
  'popularity': 95,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '3AafSrFIbJPH6BJHiJm1Cd',
  'artist_id': '6qqNVTkY8uBg9cP3Jd7DAH'},
 {'song_id': '0QZ5yyl6B6utIWkxeBDxQN',
  'song_name': 'The Night We Met',
  'duration_ms': 208211,
  'url': 'https://open.spotify.com/track/0QZ5yyl6B6utIWkxeBDxQN',
  'popularity': 83,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '3yoNZlqerJnsnMN5EDwwBS',
  'artist_id': '6ltzsmQQbmdoHHbLZ4ZN25'},
 {'song_id': '2KslE17cAJNHTsI2MI0jb2',
  'song_name': 'Standing Next to You',
  'duration_ms': 206019,
  'url': 'https://open.spotify.com/track/2KslE17cAJNHTsI2MI0jb2',
  'popularity': 96,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5pSk3c3wVwnb2arb6ohCPU',
  'artist_id': '6HaGTQPmzraVmaVxvz6EUc'},
 {'song_id': '3JvrhDOgAt6p7K8mDyZwRd',
  'song_name': 'Riptide',
  'duration_ms': 204280,
  'url': 'https://open.spotify.com/track/3JvrhDOgAt6p7K8mDyZwRd',
  'popularity': 85,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5S9b8euumqMhQbMk0zzQdH',
  'artist_id': '10exVja0key0uqUkk6LJRT'},
 {'song_id': '2Zo1PcszsT9WQ0ANntJbID',
  'song_name': 'Feather',
  'duration_ms': 185552,
  'url': 'https://open.spotify.com/track/2Zo1PcszsT9WQ0ANntJbID',
  'popularity': 93,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '2g4aJTa5ejGpp0O0GKzWAQ',
  'artist_id': '74KM79TiuVKeVCqs8QtB0B'},
 {'song_id': '2HafqoJbgXdtjwCOvNEF14',
  'song_name': 'Si No Estás',
  'duration_ms': 184061,
  'url': 'https://open.spotify.com/track/2HafqoJbgXdtjwCOvNEF14',
  'popularity': 95,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '66k6EGkPtYoN44anGIsEPW',
  'artist_id': '0jbo7KFNMiIkfBR6ih0yhm'},
 {'song_id': '4Dvkj6JhhA12EX05fT7y2e',
  'song_name': 'As It Was',
  'duration_ms': 167303,
  'url': 'https://open.spotify.com/track/4Dvkj6JhhA12EX05fT7y2e',
  'popularity': 95,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5r36AJ6VOJtp00oxSkBZ5h',
  'artist_id': '6KImCVD70vtIoJWnq6nGn3'},
 {'song_id': '6uTPdRrEDeH8Fyg5L5qmeU',
  'song_name': 'Never Lose Me',
  'duration_ms': 125901,
  'url': 'https://open.spotify.com/track/6uTPdRrEDeH8Fyg5L5qmeU',
  'popularity': 91,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '4K5YnziH8o3NoEsxv8zviL',
  'artist_id': '08PvCOlef4xdOr20jFSTPd'},
 {'song_id': '1udwFobQ1JoOdWPQrp2b6u',
  'song_name': 'Surround Sound (feat. 21 Savage & Baby Tate)',
  'duration_ms': 229938,
  'url': 'https://open.spotify.com/track/1udwFobQ1JoOdWPQrp2b6u',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '4rJDCELWL0fjdmN9Gn4f4g',
  'artist_id': '6U3ybJ9UHNKEdsH7ktGBZ7'},
 {'song_id': '6CvTEtGagmzQvkUzzyKR9k',
  'song_name': 'HARLEY QUINN',
  'duration_ms': 143327,
  'url': 'https://open.spotify.com/track/6CvTEtGagmzQvkUzzyKR9k',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '3zu0hJJew2qXZNlselIQk8',
  'artist_id': '0ys2OFYzWYB5hRDLCsBqxt'},
 {'song_id': '1yeB8MUNeLo9Ek1UEpsyz6',
  'song_name': 'Rich Baby Daddy (feat. Sexyy Red & SZA)',
  'duration_ms': 319191,
  'url': 'https://open.spotify.com/track/1yeB8MUNeLo9Ek1UEpsyz6',
  'popularity': 93,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '4czdORdCWP9umpbhFXK2fW',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '5PyDJG7SQRgWXefgexqIge',
  'song_name': 'Agora Hills',
  'duration_ms': 265360,
  'url': 'https://open.spotify.com/track/5PyDJG7SQRgWXefgexqIge',
  'popularity': 86,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '1bBez9PNvkJPW08bU7NYta',
  'artist_id': '5cj0lLjcoR7YOSnhnX0Po5'},
 {'song_id': '4KULAymBBJcPRpk1yO4dOG',
  'song_name': 'I Remember Everything (feat. Kacey Musgraves)',
  'duration_ms': 227195,
  'url': 'https://open.spotify.com/track/4KULAymBBJcPRpk1yO4dOG',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '6PbnGueEO6LGodPfvNldYf',
  'artist_id': '40ZNYROS4zLfyyBSs2PGe2'},
 {'song_id': '1odExI7RdWc4BT515LTAwj',
  'song_name': 'Daylight',
  'duration_ms': 212953,
  'url': 'https://open.spotify.com/track/1odExI7RdWc4BT515LTAwj',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '6NcI39WPu4kY6Tul11nhSv',
  'artist_id': '33NVpKoXjItPwUJTMZIOiY'},
 {'song_id': '59NraMJsLaMCVtwXTSia8i',
  'song_name': 'Prada',
  'duration_ms': 132359,
  'url': 'https://open.spotify.com/track/59NraMJsLaMCVtwXTSia8i',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5MU0RmBSpoSxOPYBfcobDc',
  'artist_id': '5wCmhq5J2hPwL2r0eKurxn'},
 {'song_id': '3AJwUDP919kvQ9QcozQPxg',
  'song_name': 'Yellow',
  'duration_ms': 266773,
  'url': 'https://open.spotify.com/track/3AJwUDP919kvQ9QcozQPxg',
  'popularity': 93,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '6ZG5lRT77aJ3btmArcykra',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU'},
 {'song_id': '1vYXt7VSjH9JIM5oRRo7vA',
  'song_name': 'Dance The Night - From Barbie The Album',
  'duration_ms': 176579,
  'url': 'https://open.spotify.com/track/1vYXt7VSjH9JIM5oRRo7vA',
  'popularity': 93,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5cH7FqB7JD5q1tJXJ7FHYu',
  'artist_id': '6M2wZ9GZgrQXHCFfjv46we'},
 {'song_id': '4bw8mcDUSRWfQo63ZTYRnU',
  'song_name': 'Según Quién',
  'duration_ms': 142334,
  'url': 'https://open.spotify.com/track/4bw8mcDUSRWfQo63ZTYRnU',
  'popularity': 90,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '3Fk8yQvPlCHgwR2pNhEIRA',
  'artist_id': '1r4hJ1h58CWwUQe3MxPuau'},
 {'song_id': '2yUzr8Sr6ldG8vmHhZwTnz',
  'song_name': 'née-nah',
  'duration_ms': 220584,
  'url': 'https://open.spotify.com/track/2yUzr8Sr6ldG8vmHhZwTnz',
  'popularity': 90,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '2RRYaYHY7fIIdvFlvgb5vq',
  'artist_id': '1URnnhqYAYcrqrcwql10ft'},
 {'song_id': '2LBqCSwhJGcFQeTHMVGwy3',
  'song_name': 'Die For You',
  'duration_ms': 260253,
  'url': 'https://open.spotify.com/track/2LBqCSwhJGcFQeTHMVGwy3',
  'popularity': 91,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '4AdZV63ycxFLF6Hcol0QnB',
  'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ'},
 {'song_id': '7DSAEUvxU8FajXtRloy8M0',
  'song_name': 'Flowers',
  'duration_ms': 200600,
  'url': 'https://open.spotify.com/track/7DSAEUvxU8FajXtRloy8M0',
  'popularity': 94,
  'song_added': '2024-01-26T16:09:07Z',
  'album_id': '5DvJgsMLbaR1HmAI6VhfcQ',
  'artist_id': '5YGY8feqx7naU7z4HrwZM6'}]

### Convert to DataFrame

In [32]:
import pandas as pd

In [34]:
album_df = pd.DataFrame.from_dict(album_list)
#drop duplicates
album_df = album_df.drop_duplicates(subset = ['album_id'])

,album_id,name,release_date,total_tracks,url
0,2IoSjweCu07y9mv5H1Cj3v,La Diabla,2023-11-30,1,https://open.spotify.com/album/2IoSjweCu07y9mv...
1,2B9amdrHDIKOoEiPUfZGtb,"yes, and?",2024-01-12,1,https://open.spotify.com/album/2B9amdrHDIKOoEi...
2,3UOV8XvCwMKaATRNXrYCjN,greedy,2023-09-15,1,https://open.spotify.com/album/3UOV8XvCwMKaATR...
3,6VCO0fDBGbRW8mCEvV95af,Lovin On Me,2023-11-10,1,https://open.spotify.com/album/6VCO0fDBGbRW8mC...
4,7tzVd1fwkxsorytCBjEJkU,The Idol Episode 4 (Music from the HBO Origina...,2023-06-23,3,https://open.spotify.com/album/7tzVd1fwkxsoryt...

In [39]:
artist_df = pd.DataFrame.from_dict(artist_list)
#drop duplicates
artist_df = artist_df.drop_duplicates(subset = ['artist_id'])

,artist_id,artist_name,external_url
0,3Me35AWHCGqW4sZ7bWWJt1,Xavi,https://api.spotify.com/v1/artists/3Me35AWHCGq...
1,66CXWjxzNUsdJxJ2JdwvnR,Ariana Grande,https://api.spotify.com/v1/artists/66CXWjxzNUs...
2,45dkTj5sMRSjrmBSBeiHym,Tate McRae,https://api.spotify.com/v1/artists/45dkTj5sMRS...
3,2LIk90788K0zvyj2JJVwkJ,Jack Harlow,https://api.spotify.com/v1/artists/2LIk90788K0...
4,1Xyo4u8uXC1ZmMpatF05PJ,The Weeknd,https://api.spotify.com/v1/artists/1Xyo4u8uXC1...
...,...,...,...
68,1r4hJ1h58CWwUQe3MxPuau,Maluma,https://api.spotify.com/v1/artists/1r4hJ1h58CW...
69,66ihevNkSYNzRAl44dx6jJ,Carin Leon,https://api.spotify.com/v1/artists/66ihevNkSYN...
71,0Y5tJX1MQlPlqiwlOH1tJY,Travis Scott,https://api.spotify.com/v1/artists/0Y5tJX1MQlP...
72,0iEtIxbK0KxaSlF7G42ZOp,Metro Boomin,https://api.spotify.com/v1/artists/0iEtIxbK0Kx...
74,5YGY8feqx7naU7z4HrwZM6,Miley Cyrus,https://api.spotify.com/v1/artists/5YGY8feqx7n...

In [41]:
song_df = pd.DataFrame.from_dict(song_list)

In [47]:
#correct the datatype of 'release_date'
album_df['release_date'] = pd.to_datetime(album_df['release_date'])
album_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      47 non-null     object
 1   name          47 non-null     object
 2   release_date  47 non-null     datetime64[ns]
 3   total_tracks  47 non-null     int64
 4   url           47 non-null     object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 2.2+ KB

In [48]:
#correct the datatype of 'song_added'
song_df['song_added'] = pd.to_datetime(song_df['song_added'])
song_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      50 non-null     object
 1   song_name    50 non-null     object
 2   duration_ms  50 non-null     int64
 3   url          50 non-null     object
 4   popularity   50 non-null     int64
 5   song_added   50 non-null     datetime64[ns, UTC]
 6   album_id     50 non-null     object
 7   artist_id    50 non-null     object
dtypes: datetime64[ns, UTC](1), int64(2), object(5)
memory usage: 3.5+ KB

In [49]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,2IoSjweCu07y9mv5H1Cj3v,La Diabla,2023-11-30,1,https://open.spotify.com/album/2IoSjweCu07y9mv...
1,2B9amdrHDIKOoEiPUfZGtb,"yes, and?",2024-01-12,1,https://open.spotify.com/album/2B9amdrHDIKOoEi...
2,3UOV8XvCwMKaATRNXrYCjN,greedy,2023-09-15,1,https://open.spotify.com/album/3UOV8XvCwMKaATR...
3,6VCO0fDBGbRW8mCEvV95af,Lovin On Me,2023-11-10,1,https://open.spotify.com/album/6VCO0fDBGbRW8mC...
4,7tzVd1fwkxsorytCBjEJkU,The Idol Episode 4 (Music from the HBO Origina...,2023-06-23,3,https://open.spotify.com/album/7tzVd1fwkxsoryt...

In [ ]:
artist_df.head()

In [50]:
song_df.head()

,song_id,song_name,duration_ms,url,popularity,song_added,album_id,artist_id
0,0R6NfOiLzLj4O5VbYSJAjf,La Diabla,172264,https://open.spotify.com/track/0R6NfOiLzLj4O5V...,99,2024-01-26 16:09:07+00:00,2IoSjweCu07y9mv5H1Cj3v,3Me35AWHCGqW4sZ7bWWJt1
1,7gaA3wERFkFkgivjwbSvkG,"yes, and?",214994,https://open.spotify.com/track/7gaA3wERFkFkgiv...,97,2024-01-26 16:09:07+00:00,2B9amdrHDIKOoEiPUfZGtb,66CXWjxzNUsdJxJ2JdwvnR
2,3rUGC1vUpkDG9CZFHMur1t,greedy,131872,https://open.spotify.com/track/3rUGC1vUpkDG9CZ...,100,2024-01-26 16:09:07+00:00,3UOV8XvCwMKaATRNXrYCjN,45dkTj5sMRSjrmBSBeiHym
3,4xhsWYTOGcal8zt0J161CU,Lovin On Me,138411,https://open.spotify.com/track/4xhsWYTOGcal8zt...,99,2024-01-26 16:09:07+00:00,6VCO0fDBGbRW8mCEvV95af,2LIk90788K0zvyj2JJVwkJ
4,7CyPwkp0oE8Ro9Dd5CUDjW,"One Of The Girls (with JENNIE, Lily Rose Depp)",244684,https://open.spotify.com/track/7CyPwkp0oE8Ro9D...,98,2024-01-26 16:09:07+00:00,7tzVd1fwkxsorytCBjEJkU,1Xyo4u8uXC1ZmMpatF05PJ