In [1]:
import spotipy
import pandas as pd
from spotipy.oauth2 import SpotifyOAuth
import os
from dotenv import load_dotenv

load_dotenv()

True

In [2]:
auth_manager = SpotifyOAuth(
    client_id=os.getenv("SPOTIFY_CLIENT_ID"),
    client_secret=os.getenv("SPOTIFY_CLIENT_SECRET"),
    redirect_uri="http://127.0.0.1:8080/callback",
    scope="playlist-read-private playlist-read-collaborative"
)

In [3]:
sp = spotipy.Spotify(auth_manager=auth_manager)

In [4]:
playlist_link = "https://open.spotify.com/playlist/3FmE8EwSfN556Gbi9Rr7NF"
playlist_URI = playlist_link.split("/")[-1]
playlist_URI

'3FmE8EwSfN556Gbi9Rr7NF'

In [5]:
#extrac data that stored in JSON file
# data = sp.playlist_tracks(playlist_URI, market='US')
data = sp.playlist(playlist_URI, market="US")
print(data)

{'collaborative': False, 'description': 'used for spark project', 'external_urls': {'spotify': 'https://open.spotify.com/playlist/3FmE8EwSfN556Gbi9Rr7NF'}, 'followers': {'href': None, 'total': 0}, 'href': 'https://api.spotify.com/v1/playlists/3FmE8EwSfN556Gbi9Rr7NF?market=US&additional_types=track', 'id': '3FmE8EwSfN556Gbi9Rr7NF', 'images': [{'height': 640, 'url': 'https://mosaic.scdn.co/640/ab67616d00001e0232a7d87248d1b75463483df5ab67616d00001e028e76f09489ebfa31ac920f08ab67616d00001e02dfa17fad7f190c901603270eab67616d00001e02f1d02a6cec967f8b6b78f76e', 'width': 640}, {'height': 300, 'url': 'https://mosaic.scdn.co/300/ab67616d00001e0232a7d87248d1b75463483df5ab67616d00001e028e76f09489ebfa31ac920f08ab67616d00001e02dfa17fad7f190c901603270eab67616d00001e02f1d02a6cec967f8b6b78f76e', 'width': 300}, {'height': 60, 'url': 'https://mosaic.scdn.co/60/ab67616d00001e0232a7d87248d1b75463483df5ab67616d00001e028e76f09489ebfa31ac920f08ab67616d00001e02dfa17fad7f190c901603270eab67616d00001e02f1d02a6cec967f8b6b78f76e', 'width': 60}], 'name': "Katie's Selected", 'owner': {'display_name': 'colcol', 'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'}, 'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh', 'id': 'xdmorvnp1mrngam9rb3xgwirh', 'type': 'user', 'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'}, 'primary_color': None, 'public': True, 'snapshot_id': 'AAAAEwo7HWpVxK3beAayA2JwzkhkYAde', 'items': {'href': 'https://api.spotify.com/v1/playlists/3FmE8EwSfN556Gbi9Rr7NF/items?offset=0&limit=100&market=US&additional_types=track', 'items': [{'added_at': '2026-05-21T00:32:20Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'}, 'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh', 'id': 'xdmorvnp1mrngam9rb3xgwirh', 'type': 'user', 'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/2ANVost0y2y52ema1E9xAZ', 'id': '2ANVost0y2y52ema1E9xAZ', 'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b27332a7d87248d1b75463483df5', 'width': 640, 'height': 640}, {'url': 'https://i.scdn.co/image/ab67616d00001e0232a7d87248d1b75463483df5', 'width': 300, 'height': 300}, {'url': 'https://i.scdn.co/image/ab67616d0000485132a7d87248d1b75463483df5', 'width': 64, 'height': 64}], 'name': 'Thriller', 'release_date': '1982-11-30', 'release_date_precision': 'day', 'uri': 'spotify:album:2ANVost0y2y52ema1E9xAZ', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm'}, 'href': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm', 'id': '3fMbdgg4jU18AjLCKBhRSm', 'name': 'Michael Jackson', 'type': 'artist', 'uri': 'spotify:artist:3fMbdgg4jU18AjLCKBhRSm'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ'}, 'total_tracks': 9}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm'}, 'href': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm', 'id': '3fMbdgg4jU18AjLCKBhRSm', 'name': 'Michael Jackson', 'type': 'artist', 'uri': 'spotify:artist:3fMbdgg4jU18AjLCKBhRSm'}], 'disc_number': 1, 'track_number': 6, 'duration_ms': 293802, 'external_ids': {'isrc': 'USSM19902991'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/7J1uxwnxfQLu4APicE5Rnj'}, 'href': 'https://api.spotify.com/v1/tracks/7J1uxwnxfQLu4APicE5Rnj', 'id': '7J1uxwnxfQLu4APicE5Rnj', 'name': 'Billie Jean', 'uri': 'spotify:track:7J1uxwnxfQLu4APicE5Rnj', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-05-21T00:32:55Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'}, 'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh', 'id': 'xdmorvnp1mrngam9rb3xgwirh', 'type': 'user', 'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/5cxMa6oLINJzmZ8lF7wWQN', 'id': '5cxMa6oLINJzmZ8lF7wWQN', 'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273f1d02a6cec967f8b6b78f76e', 'width': 640, 'height': 640}, {'url': 'https://i.scdn.co/image/ab67616d00001e02f1d02a6cec967f8b6b78f76e', 'width': 300, 'height': 300}, {'url': 'https://i.scdn.co/image/ab67616d00004851f1d02a6cec967f8b6b78f76e', 'width': 64, 'height': 64}], 'name': 'Believe', 'release_date': '2012-01-01', 'release_date_precision': 'day', 'uri': 'spotify:album:5cxMa6oLINJzmZ8lF7wWQN', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s'}, 'href': 'https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s', 'id': '1uNFoZAHBGtllmzznpCI3s', 'name': 'Justin Bieber', 'type': 'artist', 'uri': 'spotify:artist:1uNFoZAHBGtllmzznpCI3s'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/5cxMa6oLINJzmZ8lF7wWQN'}, 'total_tracks': 13}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s'}, 'href': 'https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s', 'id': '1uNFoZAHBGtllmzznpCI3s', 'name': 'Justin Bieber', 'type': 'artist', 'uri': 'spotify:artist:1uNFoZAHBGtllmzznpCI3s'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0hCNtLu0JehylgoiP8L4Gh'}, 'href': 'https://api.spotify.com/v1/artists/0hCNtLu0JehylgoiP8L4Gh', 'id': '0hCNtLu0JehylgoiP8L4Gh', 'name': 'Nicki Minaj', 'type': 'artist', 'uri': 'spotify:artist:0hCNtLu0JehylgoiP8L4Gh'}], 'disc_number': 1, 'track_number': 10, 'duration_ms': 227986, 'external_ids': {'isrc': 'USUM71205367'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/6QFCMUUq1T2Vf5sFUXcuQ7'}, 'href': 'https://api.spotify.com/v1/tracks/6QFCMUUq1T2Vf5sFUXcuQ7', 'id': '6QFCMUUq1T2Vf5sFUXcuQ7', 'name': 'Beauty And A Beat', 'uri': 'spotify:track:6QFCMUUq1T2Vf5sFUXcuQ7', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-05-21T00:32:58Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'}, 'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh', 'id': 'xdmorvnp1mrngam9rb3xgwirh', 'type': 'user', 'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/3ukkRHDHbN8tNRPKsGZR1h', 'id': '3ukkRHDHbN8tNRPKsGZR1h', 'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273dfa17fad7f190c901603270e', 'width': 640, 'height': 640}, {'url': 'https://i.scdn.co/image/ab67616d00001e02dfa17fad7f190c901603270e', 'width': 300, 'height': 300}, {'url': 'https://i.scdn.co/image/ab67616d00004851dfa17fad7f190c901603270e', 'width': 64, 'height': 64}], 'name': 'ARIRANG', 'release_date': '2026-03-20', 'release_date_precision': 'day', 'uri': 'spotify:album:3ukkRHDHbN8tNRPKsGZR1h', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Nrfpe0tUJi4K4DXYWgMUX'}, 'href': 'https://api.spotify.com/v1/artists/3Nrfpe0tUJi4K4DXYWgMUX', 'id': '3Nrfpe0tUJi4K4DXYWgMUX', 'name': 'BTS', 'type': 'artist', 'uri': 'spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/3ukkRHDHbN8tNRPKsGZR1h'}, 'total_tracks': 14}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Nrfpe0tUJi4K4DXYWgMUX'}, 'href': 'https://api.spotify.com/v1/artists/3Nrfpe0tUJi4K4DXYWgMUX', 'id': '3Nrfpe0tUJi4K4DXYWgMUX', 'name': 'BTS', 'type': 'artist', 'uri': 'spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX'}], 'disc_number': 1, 'track_number': 7, 'duration_ms': 159007, 'external_ids': {'isrc': 'USA2P2600449'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/68lbSrXDORS51pmyjZv712'}, 'href': 'https://api.spotify.com/v1/tracks/68lbSrXDORS51pmyjZv712', 'id': '68lbSrXDORS51pmyjZv712', 'name': 'SWIM', 'uri': 'spotify:track:68lbSrXDORS51pmyjZv712', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-05-21T00:33:03Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'}, 'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh', 'id': 'xdmorvnp1mrngam9rb3xgwirh', 'type': 'user', 'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': True, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/0OAv7DCME2AV4q1KPO95HY', 'id': '0OAv7DCME2AV4q1KPO95HY', 'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2738e76f09489ebfa31ac920f08', 'width': 640, 'height': 640}, {'url': 'https://i.scdn.co/image/ab67616d00001e028e76f09489ebfa31ac920f08', 'width': 300, 'height': 300}, {'url': 'https://i.scdn.co/image/ab67616d000048518e76f09489ebfa31ac920f08', 'width': 64, 'height': 64}], 'name': 'ICEMAN', 'release_date': '2026-05-15', 'release_date_precision': 'day', 'uri': 'spotify:album:0OAv7DCME2AV4q1KPO95HY', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'}, 'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4', 'id': '3TVXtAsR1Inumwj472S9r4', 'name': 'Drake', 'type': 'artist', 'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'}, 'total_tracks': 18}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'}, 'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4', 'id': '3TVXtAsR1Inumwj472S9r4', 'name': 'Drake', 'type': 'artist', 'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'}], 'disc_number': 1, 'track_number': 4, 'duration_ms': 237344, 'external_ids': {'isrc': 'USUG12604763'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/514joG57v4yKTsfQmz7stz'}, 'href': 'https://api.spotify.com/v1/tracks/514joG57v4yKTsfQmz7stz', 'id': '514joG57v4yKTsfQmz7stz', 'name': 'Janice STFU', 'uri': 'spotify:track:514joG57v4yKTsfQmz7stz', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-05-21T00:33:12Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'}, 'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh', 'id': 'xdmorvnp1mrngam9rb3xgwirh', 'type': 'user', 'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/05jbNkYoEQdjVDHEHtg1gY', 'id': '05jbNkYoEQdjVDHEHtg1gY', 'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2737b1b6f41c1645af9757d5616', 'width': 640, 'height': 640}, {'url': 'https://i.scdn.co/image/ab67616d00001e027b1b6f41c1645af9757d5616', 'width': 300, 'height': 300}, {'url': 'https://i.scdn.co/image/ab67616d000048517b1b6f41c1645af9757d5616', 'width': 64, 'height': 64}], 'name': "Don't Forget About Me, Demos", 'release_date': '2018-10-16', 'release_date_precision': 'day', 'uri': 'spotify:album:05jbNkYoEQdjVDHEHtg1gY', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6USv9qhCn6zfxlBQIYJ9qs'}, 'href': 'https://api.spotify.com/v1/artists/6USv9qhCn6zfxlBQIYJ9qs', 'id': '6USv9qhCn6zfxlBQIYJ9qs', 'name': 'Dominic Fike', 'type': 'artist', 'uri': 'spotify:artist:6USv9qhCn6zfxlBQIYJ9qs'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/05jbNkYoEQdjVDHEHtg1gY'}, 'total_tracks': 8}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6USv9qhCn6zfxlBQIYJ9qs'}, 'href': 'https://api.spotify.com/v1/artists/6USv9qhCn6zfxlBQIYJ9qs', 'id': '6USv9qhCn6zfxlBQIYJ9qs', 'name': 'Dominic Fike', 'type': 'artist', 'uri': 'spotify:artist:6USv9qhCn6zfxlBQIYJ9qs'}], 'disc_number': 1, 'track_number': 3, 'duration_ms': 97960, 'external_ids': {'isrc': 'USQX91802457'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/7yNf9YjeO5JXUE3JEBgnYc'}, 'href': 'https://api.spotify.com/v1/tracks/7yNf9YjeO5JXUE3JEBgnYc', 'id': '7yNf9YjeO5JXUE3JEBgnYc', 'name': 'Babydoll', 'uri': 'spotify:track:7yNf9YjeO5JXUE3JEBgnYc', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-05-21T01:09:33Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'}, 'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh', 'id': 'xdmorvnp1mrngam9rb3xgwirh', 'type': 'user', 'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/2ANVost0y2y52ema1E9xAZ', 'id': '2ANVost0y2y52ema1E9xAZ', 'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b27332a7d87248d1b75463483df5', 'width': 640, 'height': 640}, {'url': 'https://i.scdn.co/image/ab67616d00001e0232a7d87248d1b75463483df5', 'width': 300, 'height': 300}, {'url': 'https://i.scdn.co/image/ab67616d0000485132a7d87248d1b75463483df5', 'width': 64, 'height': 64}], 'name': 'Thriller', 'release_date': '1982-11-30', 'release_date_precision': 'day', 'uri': 'spotify:album:2ANVost0y2y52ema1E9xAZ', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm'}, 'href': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm', 'id': '3fMbdgg4jU18AjLCKBhRSm', 'name': 'Michael Jackson', 'type': 'artist', 'uri': 'spotify:artist:3fMbdgg4jU18AjLCKBhRSm'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ'}, 'total_tracks': 9}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm'}, 'href': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm', 'id': '3fMbdgg4jU18AjLCKBhRSm', 'name': 'Michael Jackson', 'type': 'artist', 'uri': 'spotify:artist:3fMbdgg4jU18AjLCKBhRSm'}], 'disc_number': 1, 'track_number': 5, 'duration_ms': 258296, 'external_ids': {'isrc': 'USSM19902990'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/3BovdzfaX4jb5KFQwoPfAw'}, 'href': 'https://api.spotify.com/v1/tracks/3BovdzfaX4jb5KFQwoPfAw', 'id': '3BovdzfaX4jb5KFQwoPfAw', 'name': 'Beat It', 'uri': 'spotify:track:3BovdzfaX4jb5KFQwoPfAw', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-05-21T01:09:44Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'}, 'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh', 'id': 'xdmorvnp1mrngam9rb3xgwirh', 'type': 'user', 'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': True, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/0OAv7DCME2AV4q1KPO95HY', 'id': '0OAv7DCME2AV4q1KPO95HY', 'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2738e76f09489ebfa31ac920f08', 'width': 640, 'height': 640}, {'url': 'https://i.scdn.co/image/ab67616d00001e028e76f09489ebfa31ac920f08', 'width': 300, 'height': 300}, {'url': 'https://i.scdn.co/image/ab67616d000048518e76f09489ebfa31ac920f08', 'width': 64, 'height': 64}], 'name': 'ICEMAN', 'release_date': '2026-05-15', 'release_date_precision': 'day', 'uri': 'spotify:album:0OAv7DCME2AV4q1KPO95HY', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'}, 'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4', 'id': '3TVXtAsR1Inumwj472S9r4', 'name': 'Drake', 'type': 'artist', 'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'}, 'total_tracks': 18}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'}, 'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4', 'id': '3TVXtAsR1Inumwj472S9r4', 'name': 'Drake', 'type': 'artist', 'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'}], 'disc_number': 1, 'track_number': 9, 'duration_ms': 200830, 'external_ids': {'isrc': 'USUG12604768'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/393OFJFZKIIv66JmJcNm9D'}, 'href': 'https://api.spotify.com/v1/tracks/393OFJFZKIIv66JmJcNm9D', 'id': '393OFJFZKIIv66JmJcNm9D', 'name': 'National Treasures', 'uri': 'spotify:track:393OFJFZKIIv66JmJcNm9D', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-05-21T01:11:13Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'}, 'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh', 'id': 'xdmorvnp1mrngam9rb3xgwirh', 'type': 'user', 'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': True, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/0OAv7DCME2AV4q1KPO95HY', 'id': '0OAv7DCME2AV4q1KPO95HY', 'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2738e76f09489ebfa31ac920f08', 'width': 640, 'height': 640}, {'url': 'https://i.scdn.co/image/ab67616d00001e028e76f09489ebfa31ac920f08', 'width': 300, 'height': 300}, {'url': 'https://i.scdn.co/image/ab67616d000048518e76f09489ebfa31ac920f08', 'width': 64, 'height': 64}], 'name': 'ICEMAN', 'release_date': '2026-05-15', 'release_date_precision': 'day', 'uri': 'spotify:album:0OAv7DCME2AV4q1KPO95HY', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'}, 'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4', 'id': '3TVXtAsR1Inumwj472S9r4', 'name': 'Drake', 'type': 'artist', 'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'}, 'total_tracks': 18}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'}, 'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4', 'id': '3TVXtAsR1Inumwj472S9r4', 'name': 'Drake', 'type': 'artist', 'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1RyvyyTE3xzB2ZywiAwp0i'}, 'href': 'https://api.spotify.com/v1/artists/1RyvyyTE3xzB2ZywiAwp0i', 'id': '1RyvyyTE3xzB2ZywiAwp0i', 'name': 'Future', 'type': 'artist', 'uri': 'spotify:artist:1RyvyyTE3xzB2ZywiAwp0i'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1zEHBw7xQf0drXZagRkciU'}, 'href': 'https://api.spotify.com/v1/artists/1zEHBw7xQf0drXZagRkciU', 'id': '1zEHBw7xQf0drXZagRkciU', 'name': 'Molly Santana', 'type': 'artist', 'uri': 'spotify:artist:1zEHBw7xQf0drXZagRkciU'}], 'disc_number': 1, 'track_number': 5, 'duration_ms': 247183, 'external_ids': {'isrc': 'USUG12604764'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/3DK90400cDlV5WUJPraMph'}, 'href': 'https://api.spotify.com/v1/tracks/3DK90400cDlV5WUJPraMph', 'id': '3DK90400cDlV5WUJPraMph', 'name': 'Ran To Atlanta (feat. Future & Molly Santana)', 'uri': 'spotify:track:3DK90400cDlV5WUJPraMph', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-05-21T01:11:18Z', 'added_by': {'externa

In [6]:
#this dataset contains info about 50 songs (tracks), the info I need stored in 'item'
len(data['items']['items'])

50

In [7]:
# Let's check the first track:
data['items']['items'][0]

{'added_at': '2026-05-21T00:32:20Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/xdmorvnp1mrngam9rb3xgwirh'},
  'href': 'https://api.spotify.com/v1/users/xdmorvnp1mrngam9rb3xgwirh',
  'id': 'xdmorvnp1mrngam9rb3xgwirh',
  'type': 'user',
  'uri': 'spotify:user:xdmorvnp1mrngam9rb3xgwirh'},
 'is_local': False,
 'primary_color': None,
 'item': {'is_playable': True,
  'explicit': False,
  'type': 'track',
  'episode': False,
  'track': True,
  'album': {'is_playable': True,
   'type': 'album',
   'album_type': 'album',
   'href': 'https://api.spotify.com/v1/albums/2ANVost0y2y52ema1E9xAZ',
   'id': '2ANVost0y2y52ema1E9xAZ',
   'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b27332a7d87248d1b75463483df5',
     'width': 640,
     'height': 640},
    {'url': 'https://i.scdn.co/image/ab67616d00001e0232a7d87248d1b75463483df5',
     'width': 300,
     'height': 300},
    {'url': 'https://i.scdn.co/image/ab67616d0000485132a7d87248d1b75463483df5',
     'width': 64,
     'height': 64}],
   'name': 'Thriller',
   'release_date': '1982-11-30',
   'release_date_precision': 'day',
   'uri': 'spotify:album:2ANVost0y2y52ema1E9xAZ',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm'},
     'href': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm',
     'id': '3fMbdgg4jU18AjLCKBhRSm',
     'name': 'Michael Jackson',
     'type': 'artist',
     'uri': 'spotify:artist:3fMbdgg4jU18AjLCKBhRSm'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ'},
   'total_tracks': 9},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm'},
    'href': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm',
    'id': '3fMbdgg4jU18AjLCKBhRSm',
    'name': 'Michael Jackson',
    'type': 'artist',
    'uri': 'spotify:artist:3fMbdgg4jU18AjLCKBhRSm'}],
  'disc_number': 1,
  'track_number': 6,
  'duration_ms': 293802,
  'external_ids': {'isrc': 'USSM19902991'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/7J1uxwnxfQLu4APicE5Rnj'},
  'href': 'https://api.spotify.com/v1/tracks/7J1uxwnxfQLu4APicE5Rnj',
  'id': '7J1uxwnxfQLu4APicE5Rnj',
  'name': 'Billie Jean',
  'uri': 'spotify:track:7J1uxwnxfQLu4APicE5Rnj',
  'is_local': False},
 'video_thumbnail': {'url': None}}

### Parse JSON to get structured data of albums

In [8]:
data['items']['items'][0]['item']['album']['id']  #album_id

'2ANVost0y2y52ema1E9xAZ'

In [9]:
data['items']['items'][0]['item']['album']['name'] #album name

'Thriller'

In [10]:
data['items']['items'][0]['item']['album']['release_date'] #release date

'1982-11-30'

In [11]:
data['items']['items'][0]['item']['album']['total_tracks'] #total tracks

9

In [12]:
data['items']['items'][0]['item']['album']['external_urls']['spotify'] #album_url

'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ'

In [13]:
#structure the data for Album
album_list = []
for row in data['items']['items']:
    album_id = row['item']['album']['id']
    album_name = row['item']['album']['name']
    album_release_date = row['item']['album']['release_date']
    album_total_tracks = row['item']['album']['total_tracks']
    album_url = row['item']['album']['external_urls']['spotify']
    album_element = {'album_id' : album_id,
                    'name' : album_name,
                    'release_date' : album_release_date,
                    'total_tracks' : album_total_tracks,
                    'url' : album_url}
    album_list.append(album_element)

In [14]:
album_list

[{'album_id': '2ANVost0y2y52ema1E9xAZ',
  'name': 'Thriller',
  'release_date': '1982-11-30',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ'},
 {'album_id': '5cxMa6oLINJzmZ8lF7wWQN',
  'name': 'Believe',
  'release_date': '2012-01-01',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/5cxMa6oLINJzmZ8lF7wWQN'},
 {'album_id': '3ukkRHDHbN8tNRPKsGZR1h',
  'name': 'ARIRANG',
  'release_date': '2026-03-20',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/3ukkRHDHbN8tNRPKsGZR1h'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '05jbNkYoEQdjVDHEHtg1gY',
  'name': "Don't Forget About Me, Demos",
  'release_date': '2018-10-16',
  'total_tracks': 8,
  'url': 'https://open.spotify.com/album/05jbNkYoEQdjVDHEHtg1gY'},
 {'album_id': '2ANVost0y2y52ema1E9xAZ',
  'name': 'Thriller',
  'release_date': '1982-11-30',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '2ANVost0y2y52ema1E9xAZ',
  'name': 'Thriller',
  'release_date': '1982-11-30',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ'},
 {'album_id': '2ZytN2cY4Zjrr9ukb2rqTP',
  'name': 'Off the Wall',
  'release_date': '1979-08-10',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/2ZytN2cY4Zjrr9ukb2rqTP'},
 {'album_id': '7mvXPtV4jvA1hp5Wx2FAJA',
  'name': 'I Barely Know Her',
  'release_date': '2025-08-22',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/7mvXPtV4jvA1hp5Wx2FAJA'},
 {'album_id': '2jX6yKrWw9bY7JAYHhhtqZ',
  'name': 'Sweet Boy',
  'release_date': '2024-04-05',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/2jX6yKrWw9bY7JAYHhhtqZ'},
 {'album_id': '2UG6T6f0Qc9SaBCIcaviLM',
  'name': 'Teenage Dream',
  'release_date': '2010-01-01',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/2UG6T6f0Qc9SaBCIcaviLM'},
 {'album_id': '4JDXBZdRPId4devseaAOKH',
  'name': 'DECIDE',
  'release_date': '2022-09-16',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/4JDXBZdRPId4devseaAOKH'},
 {'album_id': '0Bv6OJO0L5gcf20DMww54a',
  'name': 'Man I Need',
  'release_date': '2025-08-15',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/0Bv6OJO0L5gcf20DMww54a'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '6nrtxtgaD9zSYBl9APvOCH',
  'name': 'Dandelion',
  'release_date': '2026-04-10',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/6nrtxtgaD9zSYBl9APvOCH'},
 {'album_id': '6KFq3hJB6JnNvDbEHRvPoK',
  'name': 'Dracula (Remix)',
  'release_date': '2026-02-06',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/6KFq3hJB6JnNvDbEHRvPoK'},
 {'album_id': '7vI4iTxDmgEN63liQHPEX1',
  'name': 'The Romantic',
  'release_date': '2026-02-27',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/7vI4iTxDmgEN63liQHPEX1'},
 {'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'name': 'The Life of a Showgirl',
  'release_date': '2025-10-03',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/4a6NzYL1YHRUgx9e3YZI6I'},
 {'album_id': '24f1GFXCkViGoRpmGqlSSl',
  'name': 'The Boy Who Played the Harp',
  'release_date': '2025-10-23',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/24f1GFXCkViGoRpmGqlSSl'},
 {'album_id': '6yWUYijJvHyjvcw43abyWD',
  'name': 'drop dead (taken that eurostar to france video)',
  'release_date': '2026-04-16',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/6yWUYijJvHyjvcw43abyWD'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '12Lig9oAX9nvpWHft5cHgF',
  'name': 'Fancy Some More?',
  'release_date': '2025-10-10',
  'total_tracks': 31,
  'url': 'https://open.spotify.com/album/12Lig9oAX9nvpWHft5cHgF'},
 {'album_id': '1eCGY9WJpYgtaFh1Lk2KNo',
  'name': "You'll Be Alright, Kid (Chapter 1)",
  'release_date': '2024-09-26',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/1eCGY9WJpYgtaFh1Lk2KNo'},
 {'album_id': '5K79FLRUCSysQnVESLcTdb',
  'name': 'DeBÍ TiRAR MáS FOToS',
  'release_date': '2025-01-05',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/5K79FLRUCSysQnVESLcTdb'},
 {'album_id': '4UMjBXcRqIgMZ1XumU2x5T',
  'name': 'Dizzy up the Girl',
  'release_date': '1998',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/4UMjBXcRqIgMZ1XumU2x5T'},
 {'album_id': '7Cdqksm4yTfiq0EfKPa86M',
  'name': 'Self Aware',
  'release_date': '2026-02-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/7Cdqksm4yTfiq0EfKPa86M'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '5vD5M5VW62LL78Ko8x0CVZ',
  'name': 'SWAG',
  'release_date': '2025-07-11',
  'total_tracks': 21,
  'url': 'https://open.spotify.com/album/5vD5M5VW62LL78Ko8x0CVZ'},
 {'album_id': '0l8zYqoUeBYg47Gmevq9HZ',
  'name': 'The Art of Loving',
  'release_date': '2025-09-26',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/0l8zYqoUeBYg47Gmevq9HZ'},
 {'album_id': '1uE3dRPe3SrGdNhd1nWlSa',
  'name': "Bird's Eye",
  'release_date': '2024-08-09',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/1uE3dRPe3SrGdNhd1nWlSa'},
 {'album_id': '2MHUaRi9OCyTN02SoyRRBJ',
  'name': 'MAYHEM',
  'release_date': '2025-03-07',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/2MHUaRi9OCyTN02SoyRRBJ'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '4xkM0BwLM9H2IUcbYzpcBI',
  'name': 'I Love You.',
  'release_date': '2013-04-22',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/4xkM0BwLM9H2IUcbYzpcBI'},
 {'album_id': '3Us57CjssWnHjTUIXBuIeH',
  'name': 'Bad (Remastered)',
  'release_date': '1987-08-31',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/3Us57CjssWnHjTUIXBuIeH'},
 {'album_id': '7pomP86PUhoJpY3fsC0WDQ',
  'name': 'XSCAPE',
  'release_date': '2014-05-09',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/7pomP86PUhoJpY3fsC0WDQ'},
 {'album_id': '5YLRVHDVRw3QqWbeTGpC5B',
  'name': 'So Good',
  'release_date': '2017-03-17',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/5YLRVHDVRw3QqWbeTGpC5B'},
 {'album_id': '7aJuG4TFXa2hmE4z1yxc3n',
  'name': 'HIT ME HARD AND SOFT',
  'release_date': '2024-05-17',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/7aJuG4TFXa2hmE4z1yxc3n'},
 {'album_id': '3ZN01xzenGMhWHdC5kfAe9',
  'name': 'THIS MUSIC MAY CONTAIN HOPE.',
  'release_date': '2026-03-27',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/3ZN01xzenGMhWHdC5kfAe9'},
 {'album_id': '4piJq7R3gjUOxnYs6lDCTg',
  'name': 'Hot Fuss',
  'release_date': '2004',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/4piJq7R3gjUOxnYs6lDCTg'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY'},
 {'album_id': '0PRccyeXfXZBxi8dkIv17c',
  'name': 'White Keys',
  'release_date': '2025-11-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0PRccyeXfXZBxi8dkIv17c'},
 {'album_id': '14JkAa6IiFaOh5s0nMyMU9',
  'name': 'KPop Demon Hunters (Soundtrack from the Netflix Film)',
  'release_date': '2025-06-20',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/14JkAa6IiFaOh5s0nMyMU9'},
 {'album_id': '5K79FLRUCSysQnVESLcTdb',
  'name': 'DeBÍ TiRAR MáS FOToS',
  'release_date': '2025-01-05',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/5K79FLRUCSysQnVESLcTdb'},
 {'album_id': '58vZavXqh1P5uoTXteudWl',
  'name': 'At The Beach, In Every Life',
  'release_date': '2025-04-25',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/58vZavXqh1P5uoTXteudWl'}]

### Parse JSON to get structured data of artists

In [15]:
#similar to album, I also want to try the second method to extract artist data.
artist_list = []
for row in data['items']['items']:
    for key, value in row.items():
        if key == 'item':
            for artist in value['artists']:
                artist_dict = {'artist_id' : artist['id'],
                'artist_name' : artist['name'],
                'external_url' : artist['href'],
                }
                artist_list.append(artist_dict)

In [16]:
artist_list

[{'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'artist_name': 'Michael Jackson',
  'external_url': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm'},
 {'artist_id': '1uNFoZAHBGtllmzznpCI3s',
  'artist_name': 'Justin Bieber',
  'external_url': 'https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s'},
 {'artist_id': '0hCNtLu0JehylgoiP8L4Gh',
  'artist_name': 'Nicki Minaj',
  'external_url': 'https://api.spotify.com/v1/artists/0hCNtLu0JehylgoiP8L4Gh'},
 {'artist_id': '3Nrfpe0tUJi4K4DXYWgMUX',
  'artist_name': 'BTS',
  'external_url': 'https://api.spotify.com/v1/artists/3Nrfpe0tUJi4K4DXYWgMUX'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '6USv9qhCn6zfxlBQIYJ9qs',
  'artist_name': 'Dominic Fike',
  'external_url': 'https://api.spotify.com/v1/artists/6USv9qhCn6zfxlBQIYJ9qs'},
 {'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'artist_name': 'Michael Jackson',
  'external_url': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '1RyvyyTE3xzB2ZywiAwp0i',
  'artist_name': 'Future',
  'external_url': 'https://api.spotify.com/v1/artists/1RyvyyTE3xzB2ZywiAwp0i'},
 {'artist_id': '1zEHBw7xQf0drXZagRkciU',
  'artist_name': 'Molly Santana',
  'external_url': 'https://api.spotify.com/v1/artists/1zEHBw7xQf0drXZagRkciU'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'artist_name': 'Michael Jackson',
  'external_url': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm'},
 {'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'artist_name': 'Michael Jackson',
  'external_url': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm'},
 {'artist_id': '4G9NDjRyZFDlJKMRL8hx3S',
  'artist_name': 'sombr',
  'external_url': 'https://api.spotify.com/v1/artists/4G9NDjRyZFDlJKMRL8hx3S'},
 {'artist_id': '7eKkW1zo5uzW8kUntiiBvz',
  'artist_name': 'Malcolm Todd',
  'external_url': 'https://api.spotify.com/v1/artists/7eKkW1zo5uzW8kUntiiBvz'},
 {'artist_id': '6jJ0s89eD6GaHleKKya26X',
  'artist_name': 'Katy Perry',
  'external_url': 'https://api.spotify.com/v1/artists/6jJ0s89eD6GaHleKKya26X'},
 {'artist_id': '5p9HO3XC5P3BLxJs5Mtrhm',
  'artist_name': 'Djo',
  'external_url': 'https://api.spotify.com/v1/artists/5p9HO3XC5P3BLxJs5Mtrhm'},
 {'artist_id': '00x1fYSGhdqScXBRpSj3DW',
  'artist_name': 'Olivia Dean',
  'external_url': 'https://api.spotify.com/v1/artists/00x1fYSGhdqScXBRpSj3DW'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '6BRxQ8cD3eqnrVj6WKDok8',
  'artist_name': 'Ella Langley',
  'external_url': 'https://api.spotify.com/v1/artists/6BRxQ8cD3eqnrVj6WKDok8'},
 {'artist_id': '5INjqkS1o8h1imAzPqGZBb',
  'artist_name': 'Tame Impala',
  'external_url': 'https://api.spotify.com/v1/artists/5INjqkS1o8h1imAzPqGZBb'},
 {'artist_id': '250b0Wlc5Vk0CoUsaCY84M',
  'artist_name': 'JENNIE',
  'external_url': 'https://api.spotify.com/v1/artists/250b0Wlc5Vk0CoUsaCY84M'},
 {'artist_id': '0du5cEVh5yTK9QJze8zA0C',
  'artist_name': 'Bruno Mars',
  'external_url': 'https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C'},
 {'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift',
  'external_url': 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02'},
 {'artist_id': '6Ip8FS7vWT1uKkJSweANQK',
  'artist_name': 'Dave',
  'external_url': 'https://api.spotify.com/v1/artists/6Ip8FS7vWT1uKkJSweANQK'},
 {'artist_id': '687cZJR45JO7jhk1LHIbgq',
  'artist_name': 'Tems',
  'external_url': 'https://api.spotify.com/v1/artists/687cZJR45JO7jhk1LHIbgq'},
 {'artist_id': '1McMsnEElThX1knmY4oliG',
  'artist_name': 'Olivia Rodrigo',
  'external_url': 'https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '78rUTD7y6Cy67W1RVzYs7t',
  'artist_name': 'PinkPantheress',
  'external_url': 'https://api.spotify.com/v1/artists/78rUTD7y6Cy67W1RVzYs7t'},
 {'artist_id': '1Xylc3o4UrD53lo9CvFvVg',
  'artist_name': 'Zara Larsson',
  'external_url': 'https://api.spotify.com/v1/artists/1Xylc3o4UrD53lo9CvFvVg'},
 {'artist_id': '0fTSzq9jAh4c36UVb4V7CB',
  'artist_name': 'Alex Warren',
  'external_url': 'https://api.spotify.com/v1/artists/0fTSzq9jAh4c36UVb4V7CB'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '2sil8z5kiy4r76CRTXxBCA',
  'artist_name': 'The Goo Goo Dolls',
  'external_url': 'https://api.spotify.com/v1/artists/2sil8z5kiy4r76CRTXxBCA'},
 {'artist_id': '5mHUmlJWkcoOk1NbjfrXWz',
  'artist_name': 'Temper City',
  'external_url': 'https://api.spotify.com/v1/artists/5mHUmlJWkcoOk1NbjfrXWz'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '1uNFoZAHBGtllmzznpCI3s',
  'artist_name': 'Justin Bieber',
  'external_url': 'https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s'},
 {'artist_id': '00x1fYSGhdqScXBRpSj3DW',
  'artist_name': 'Olivia Dean',
  'external_url': 'https://api.spotify.com/v1/artists/00x1fYSGhdqScXBRpSj3DW'},
 {'artist_id': '5RTLRtXjbXI2lSXc6jxlAz',
  'artist_name': 'Ravyn Lenae',
  'external_url': 'https://api.spotify.com/v1/artists/5RTLRtXjbXI2lSXc6jxlAz'},
 {'artist_id': '1HY2Jd0NmPuamShAr6KMms',
  'artist_name': 'Lady Gaga',
  'external_url': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms'},
 {'artist_id': '0du5cEVh5yTK9QJze8zA0C',
  'artist_name': 'Bruno Mars',
  'external_url': 'https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '77SW9BnxLY8rJ0RciFqkHh',
  'artist_name': 'The Neighbourhood',
  'external_url': 'https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh'},
 {'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'artist_name': 'Michael Jackson',
  'external_url': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm'},
 {'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'artist_name': 'Michael Jackson',
  'external_url': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm'},
 {'artist_id': '1Xylc3o4UrD53lo9CvFvVg',
  'artist_name': 'Zara Larsson',
  'external_url': 'https://api.spotify.com/v1/artists/1Xylc3o4UrD53lo9CvFvVg'},
 {'artist_id': '6qqNVTkY8uBg9cP3Jd7DAH',
  'artist_name': 'Billie Eilish',
  'external_url': 'https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH'},
 {'artist_id': '5KKpBU5eC2tJDzf0wmlRp2',
  'artist_name': 'RAYE',
  'external_url': 'https://api.spotify.com/v1/artists/5KKpBU5eC2tJDzf0wmlRp2'},
 {'artist_id': '0C0XlULifJtAgn6ZNCW2eu',
  'artist_name': 'The Killers',
  'external_url': 'https://api.spotify.com/v1/artists/0C0XlULifJtAgn6ZNCW2eu'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '1URnnhqYAYcrqrcwql10ft',
  'artist_name': '21 Savage',
  'external_url': 'https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '6USv9qhCn6zfxlBQIYJ9qs',
  'artist_name': 'Dominic Fike',
  'external_url': 'https://api.spotify.com/v1/artists/6USv9qhCn6zfxlBQIYJ9qs'},
 {'artist_id': '2yNNYQBChuox9A5Ka93BIn',
  'artist_name': 'HUNTR/X',
  'external_url': 'https://api.spotify.com/v1/artists/2yNNYQBChuox9A5Ka93BIn'},
 {'artist_id': '0RMJOzHDhAKY1o2j0W0vxY',
  'artist_name': 'EJAE',
  'external_url': 'https://api.spotify.com/v1/artists/0RMJOzHDhAKY1o2j0W0vxY'},
 {'artist_id': '0Wwji82sLA0Hcvtuak3omb',
  'artist_name': 'AUDREY NUNA',
  'external_url': 'https://api.spotify.com/v1/artists/0Wwji82sLA0Hcvtuak3omb'},
 {'artist_id': '6U1dV7aL68N7Gb0Naq34V5',
  'artist_name': 'REI AMI',
  'external_url': 'https://api.spotify.com/v1/artists/6U1dV7aL68N7Gb0Naq34V5'},
 {'artist_id': '7mW7Tv7NvywKKXqafZo0Lc',
  'artist_name': 'KPop Demon Hunters Cast',
  'external_url': 'https://api.spotify.com/v1/artists/7mW7Tv7NvywKKXqafZo0Lc'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '1iCnM8foFssWlPRLfAbIwo',
  'artist_name': 'Gigi Perez',
  'external_url': 'https://api.spotify.com/v1/artists/1iCnM8foFssWlPRLfAbIwo'}]

### Parse JSON to get structured data of songs

In [17]:
song_list = []
for row in data['items']['items']:
    song_id = row['item']['id']
    song_name = row['item']['name']
    song_duration = row['item']['duration_ms']
    song_url = row['item']['external_urls']['spotify']
    song_popularity = row['item'].get('popularity', None)
    song_added = row['added_at']
    album_id = row['item']['album']['id']
    artist_id = row['item']['album']['artists'][0]['id']
    song_element = {'song_id':song_id,'song_name':song_name,'duration_ms':song_duration,'url':song_url,
                    'popularity':song_popularity,'song_added':song_added,'album_id':album_id,
                    'artist_id':artist_id
                   }
    song_list.append(song_element)

In [18]:
song_list

[{'song_id': '7J1uxwnxfQLu4APicE5Rnj',
  'song_name': 'Billie Jean',
  'duration_ms': 293802,
  'url': 'https://open.spotify.com/track/7J1uxwnxfQLu4APicE5Rnj',
  'popularity': None,
  'song_added': '2026-05-21T00:32:20Z',
  'album_id': '2ANVost0y2y52ema1E9xAZ',
  'artist_id': '3fMbdgg4jU18AjLCKBhRSm'},
 {'song_id': '6QFCMUUq1T2Vf5sFUXcuQ7',
  'song_name': 'Beauty And A Beat',
  'duration_ms': 227986,
  'url': 'https://open.spotify.com/track/6QFCMUUq1T2Vf5sFUXcuQ7',
  'popularity': None,
  'song_added': '2026-05-21T00:32:55Z',
  'album_id': '5cxMa6oLINJzmZ8lF7wWQN',
  'artist_id': '1uNFoZAHBGtllmzznpCI3s'},
 {'song_id': '68lbSrXDORS51pmyjZv712',
  'song_name': 'SWIM',
  'duration_ms': 159007,
  'url': 'https://open.spotify.com/track/68lbSrXDORS51pmyjZv712',
  'popularity': None,
  'song_added': '2026-05-21T00:32:58Z',
  'album_id': '3ukkRHDHbN8tNRPKsGZR1h',
  'artist_id': '3Nrfpe0tUJi4K4DXYWgMUX'},
 {'song_id': '514joG57v4yKTsfQmz7stz',
  'song_name': 'Janice STFU',
  'duration_ms': 237344,
  'url': 'https://open.spotify.com/track/514joG57v4yKTsfQmz7stz',
  'popularity': None,
  'song_added': '2026-05-21T00:33:03Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '7yNf9YjeO5JXUE3JEBgnYc',
  'song_name': 'Babydoll',
  'duration_ms': 97960,
  'url': 'https://open.spotify.com/track/7yNf9YjeO5JXUE3JEBgnYc',
  'popularity': None,
  'song_added': '2026-05-21T00:33:12Z',
  'album_id': '05jbNkYoEQdjVDHEHtg1gY',
  'artist_id': '6USv9qhCn6zfxlBQIYJ9qs'},
 {'song_id': '3BovdzfaX4jb5KFQwoPfAw',
  'song_name': 'Beat It',
  'duration_ms': 258296,
  'url': 'https://open.spotify.com/track/3BovdzfaX4jb5KFQwoPfAw',
  'popularity': None,
  'song_added': '2026-05-21T01:09:33Z',
  'album_id': '2ANVost0y2y52ema1E9xAZ',
  'artist_id': '3fMbdgg4jU18AjLCKBhRSm'},
 {'song_id': '393OFJFZKIIv66JmJcNm9D',
  'song_name': 'National Treasures',
  'duration_ms': 200830,
  'url': 'https://open.spotify.com/track/393OFJFZKIIv66JmJcNm9D',
  'popularity': None,
  'song_added': '2026-05-21T01:09:44Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '3DK90400cDlV5WUJPraMph',
  'song_name': 'Ran To Atlanta (feat. Future & Molly Santana)',
  'duration_ms': 247183,
  'url': 'https://open.spotify.com/track/3DK90400cDlV5WUJPraMph',
  'popularity': None,
  'song_added': '2026-05-21T01:11:13Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '7KGHenqXZofXNm5MKDbT3J',
  'song_name': 'Whisper My Name',
  'duration_ms': 222580,
  'url': 'https://open.spotify.com/track/7KGHenqXZofXNm5MKDbT3J',
  'popularity': None,
  'song_added': '2026-05-21T01:11:18Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '6vjpQIdABqntoe3zPazPec',
  'song_name': 'Shabang',
  'duration_ms': 188722,
  'url': 'https://open.spotify.com/track/6vjpQIdABqntoe3zPazPec',
  'popularity': None,
  'song_added': '2026-05-21T01:11:24Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '4cgjA7B4fJBHyB9Ya2bu0t',
  'song_name': 'Human Nature',
  'duration_ms': 245837,
  'url': 'https://open.spotify.com/track/4cgjA7B4fJBHyB9Ya2bu0t',
  'popularity': None,
  'song_added': '2026-05-21T01:11:28Z',
  'album_id': '2ANVost0y2y52ema1E9xAZ',
  'artist_id': '3fMbdgg4jU18AjLCKBhRSm'},
 {'song_id': '46eu3SBuFCXWsPT39Yg3tJ',
  'song_name': "Don't Stop 'Til You Get Enough",
  'duration_ms': 364441,
  'url': 'https://open.spotify.com/track/46eu3SBuFCXWsPT39Yg3tJ',
  'popularity': None,
  'song_added': '2026-05-21T01:11:31Z',
  'album_id': '2ZytN2cY4Zjrr9ukb2rqTP',
  'artist_id': '3fMbdgg4jU18AjLCKBhRSm'},
 {'song_id': '7qjZnBKE73H4Oxkopwulqe',
  'song_name': 'back to friends',
  'duration_ms': 199032,
  'url': 'https://open.spotify.com/track/7qjZnBKE73H4Oxkopwulqe',
  'popularity': None,
  'song_added': '2026-05-21T01:11:38Z',
  'album_id': '7mvXPtV4jvA1hp5Wx2FAJA',
  'artist_id': '4G9NDjRyZFDlJKMRL8hx3S'},
 {'song_id': '0eAuGrXyGFYwur9ARUe7LJ',
  'song_name': 'Earrings',
  'duration_ms': 151500,
  'url': 'https://open.spotify.com/track/0eAuGrXyGFYwur9ARUe7LJ',
  'popularity': None,
  'song_added': '2026-05-21T01:11:42Z',
  'album_id': '2jX6yKrWw9bY7JAYHhhtqZ',
  'artist_id': '7eKkW1zo5uzW8kUntiiBvz'},
 {'song_id': '2009X8GyWTqyxIdzAEYW6N',
  'song_name': 'The One That Got Away',
  'duration_ms': 227333,
  'url': 'https://open.spotify.com/track/2009X8GyWTqyxIdzAEYW6N',
  'popularity': None,
  'song_added': '2026-05-21T01:11:45Z',
  'album_id': '2UG6T6f0Qc9SaBCIcaviLM',
  'artist_id': '6jJ0s89eD6GaHleKKya26X'},
 {'song_id': '3qhlB30KknSejmIvZZLjOD',
  'song_name': 'End of Beginning',
  'duration_ms': 159245,
  'url': 'https://open.spotify.com/track/3qhlB30KknSejmIvZZLjOD',
  'popularity': None,
  'song_added': '2026-05-21T01:12:02Z',
  'album_id': '4JDXBZdRPId4devseaAOKH',
  'artist_id': '5p9HO3XC5P3BLxJs5Mtrhm'},
 {'song_id': '1qbmS6ep2hbBRaEZFpn7BX',
  'song_name': 'Man I Need',
  'duration_ms': 184000,
  'url': 'https://open.spotify.com/track/1qbmS6ep2hbBRaEZFpn7BX',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0Bv6OJO0L5gcf20DMww54a',
  'artist_id': '00x1fYSGhdqScXBRpSj3DW'},
 {'song_id': '7COiiObIVJIdBcW3J43Iy2',
  'song_name': '2 Hard 4 The Radio',
  'duration_ms': 183500,
  'url': 'https://open.spotify.com/track/7COiiObIVJIdBcW3J43Iy2',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '7scFxt9VhL4FJwuPSfRlfN',
  'song_name': "Choosin' Texas",
  'duration_ms': 231746,
  'url': 'https://open.spotify.com/track/7scFxt9VhL4FJwuPSfRlfN',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '6nrtxtgaD9zSYBl9APvOCH',
  'artist_id': '6BRxQ8cD3eqnrVj6WKDok8'},
 {'song_id': '5yvVYFDUpbnjcnRBgjwTzM',
  'song_name': 'Dracula - JENNIE Remix',
  'duration_ms': 209720,
  'url': 'https://open.spotify.com/track/5yvVYFDUpbnjcnRBgjwTzM',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '6KFq3hJB6JnNvDbEHRvPoK',
  'artist_id': '5INjqkS1o8h1imAzPqGZBb'},
 {'song_id': '5y2ijHECwFYWqcAHKTZgzD',
  'song_name': 'Risk It All',
  'duration_ms': 204068,
  'url': 'https://open.spotify.com/track/5y2ijHECwFYWqcAHKTZgzD',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '7vI4iTxDmgEN63liQHPEX1',
  'artist_id': '0du5cEVh5yTK9QJze8zA0C'},
 {'song_id': '53iuhJlwXhSER5J2IYYv1W',
  'song_name': 'The Fate of Ophelia',
  'duration_ms': 226073,
  'url': 'https://open.spotify.com/track/53iuhJlwXhSER5J2IYYv1W',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'artist_id': '06HL4z0CvFAxyc27GXpf02'},
 {'song_id': '3oTuTpF1F3A7rEC6RKsMRz',
  'song_name': 'Raindance (feat. Tems)',
  'duration_ms': 219743,
  'url': 'https://open.spotify.com/track/3oTuTpF1F3A7rEC6RKsMRz',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '24f1GFXCkViGoRpmGqlSSl',
  'artist_id': '6Ip8FS7vWT1uKkJSweANQK'},
 {'song_id': '7Hc6qcJG4NtyZgbNvQyd8U',
  'song_name': 'drop dead',
  'duration_ms': 224998,
  'url': 'https://open.spotify.com/track/7Hc6qcJG4NtyZgbNvQyd8U',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '6yWUYijJvHyjvcw43abyWD',
  'artist_id': '1McMsnEElThX1knmY4oliG'},
 {'song_id': '3cLCA9LSb6UiOeNvTZoaav',
  'song_name': 'Plot Twist',
  'duration_ms': 195678,
  'url': 'https://open.spotify.com/track/3cLCA9LSb6UiOeNvTZoaav',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '1DwscornXpj8fmOmYVlqZt',
  'song_name': 'Stateside + Zara Larsson',
  'duration_ms': 184761,
  'url': 'https://open.spotify.com/track/1DwscornXpj8fmOmYVlqZt',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '12Lig9oAX9nvpWHft5cHgF',
  'artist_id': '78rUTD7y6Cy67W1RVzYs7t'},
 {'song_id': '2RkZ5LkEzeHGRsmDqKwmaJ',
  'song_name': 'Ordinary',
  'duration_ms': 186964,
  'url': 'https://open.spotify.com/track/2RkZ5LkEzeHGRsmDqKwmaJ',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '1eCGY9WJpYgtaFh1Lk2KNo',
  'artist_id': '0fTSzq9jAh4c36UVb4V7CB'},
 {'song_id': '3sK8wGT43QFpWrvNQsrQya',
  'song_name': 'DtMF',
  'duration_ms': 237117,
  'url': 'https://open.spotify.com/track/3sK8wGT43QFpWrvNQsrQya',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '5K79FLRUCSysQnVESLcTdb',
  'artist_id': '4q3ewBCX7sLwd24euuV69X'},
 {'song_id': '6Qyc6fS4DsZjB2mRW9DsQs',
  'song_name': 'Iris',
  'duration_ms': 289533,
  'url': 'https://open.spotify.com/track/6Qyc6fS4DsZjB2mRW9DsQs',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '4UMjBXcRqIgMZ1XumU2x5T',
  'artist_id': '2sil8z5kiy4r76CRTXxBCA'},
 {'song_id': '4qW3BbQAwZsrnu8a3ZRdyT',
  'song_name': 'Self Aware',
  'duration_ms': 180740,
  'url': 'https://open.spotify.com/track/4qW3BbQAwZsrnu8a3ZRdyT',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '7Cdqksm4yTfiq0EfKPa86M',
  'artist_id': '5mHUmlJWkcoOk1NbjfrXWz'},
 {'song_id': '55wlsNYqcfiQsHuX8l0jmF',
  'song_name': 'Make Them Cry',
  'duration_ms': 307681,
  'url': 'https://open.spotify.com/track/55wlsNYqcfiQsHuX8l0jmF',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '4eE16RJFDKf2WxBTqqfylu',
  'song_name': 'Dust',
  'duration_ms': 189217,
  'url': 'https://open.spotify.com/track/4eE16RJFDKf2WxBTqqfylu',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '5BZsQlgw21vDOAjoqkNgKb',
  'song_name': 'DAISIES',
  'duration_ms': 176453,
  'url': 'https://open.spotify.com/track/5BZsQlgw21vDOAjoqkNgKb',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '5vD5M5VW62LL78Ko8x0CVZ',
  'artist_id': '1uNFoZAHBGtllmzznpCI3s'},
 {'song_id': '6sGIMrtIzQjdzNndVxe397',
  'song_name': 'So Easy (To Fall In Love)',
  'duration_ms': 169000,
  'url': 'https://open.spotify.com/track/6sGIMrtIzQjdzNndVxe397',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0l8zYqoUeBYg47Gmevq9HZ',
  'artist_id': '00x1fYSGhdqScXBRpSj3DW'},
 {'song_id': '4WFgvKVfEhb3IUAFGrutTR',
  'song_name': 'Love Me Not',
  'duration_ms': 213466,
  'url': 'https://open.spotify.com/track/4WFgvKVfEhb3IUAFGrutTR',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '1uE3dRPe3SrGdNhd1nWlSa',
  'artist_id': '5RTLRtXjbXI2lSXc6jxlAz'},
 {'song_id': '7so0lgd0zP2Sbgs2d7a1SZ',
  'song_name': 'Die With A Smile',
  'duration_ms': 251667,
  'url': 'https://open.spotify.com/track/7so0lgd0zP2Sbgs2d7a1SZ',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '2MHUaRi9OCyTN02SoyRRBJ',
  'artist_id': '1HY2Jd0NmPuamShAr6KMms'},
 {'song_id': '7oDbkGSI3IRzKmhrTiQdID',
  'song_name': 'What Did I Miss?',
  'duration_ms': 194324,
  'url': 'https://open.spotify.com/track/7oDbkGSI3IRzKmhrTiQdID',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '2QjOHCTQ1Jl3zawyYOpxh6',
  'song_name': 'Sweater Weather',
  'duration_ms': 240400,
  'url': 'https://open.spotify.com/track/2QjOHCTQ1Jl3zawyYOpxh6',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '4xkM0BwLM9H2IUcbYzpcBI',
  'artist_id': '77SW9BnxLY8rJ0RciFqkHh'},
 {'song_id': '5T7ywazdGIydr6JCW6t02j',
  'song_name': 'Smooth Criminal - 2012 Remaster',
  'duration_ms': 257766,
  'url': 'https://open.spotify.com/track/5T7ywazdGIydr6JCW6t02j',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '3Us57CjssWnHjTUIXBuIeH',
  'artist_id': '3fMbdgg4jU18AjLCKBhRSm'},
 {'song_id': '5BKKy9fIJL5uM9fz1SnqyP',
  'song_name': 'Chicago',
  'duration_ms': 245565,
  'url': 'https://open.spotify.com/track/5BKKy9fIJL5uM9fz1SnqyP',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '7pomP86PUhoJpY3fsC0WDQ',
  'artist_id': '3fMbdgg4jU18AjLCKBhRSm'},
 {'song_id': '1rIKgCH4H52lrvDcz50hS8',
  'song_name': 'Lush Life',
  'duration_ms': 200646,
  'url': 'https://open.spotify.com/track/1rIKgCH4H52lrvDcz50hS8',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '5YLRVHDVRw3QqWbeTGpC5B',
  'artist_id': '1Xylc3o4UrD53lo9CvFvVg'},
 {'song_id': '6dOtVTDdiauQNBQEDOtlAB',
  'song_name': 'BIRDS OF A FEATHER',
  'duration_ms': 210373,
  'url': 'https://open.spotify.com/track/6dOtVTDdiauQNBQEDOtlAB',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '7aJuG4TFXa2hmE4z1yxc3n',
  'artist_id': '6qqNVTkY8uBg9cP3Jd7DAH'},
 {'song_id': '7eYzn1CuiJK6VvUhf8zA6k',
  'song_name': 'WHERE IS MY HUSBAND!',
  'duration_ms': 197142,
  'url': 'https://open.spotify.com/track/7eYzn1CuiJK6VvUhf8zA6k',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '3ZN01xzenGMhWHdC5kfAe9',
  'artist_id': '5KKpBU5eC2tJDzf0wmlRp2'},
 {'song_id': '003vvx7Niy0yvhvHt4a68B',
  'song_name': 'Mr. Brightside',
  'duration_ms': 222973,
  'url': 'https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '4piJq7R3gjUOxnYs6lDCTg',
  'artist_id': '0C0XlULifJtAgn6ZNCW2eu'},
 {'song_id': '4ygJHbpMGwZknVFaRikdFr',
  'song_name': "B's On The Table (feat. 21 Savage)",
  'duration_ms': 137647,
  'url': 'https://open.spotify.com/track/4ygJHbpMGwZknVFaRikdFr',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '57rkFdhoKjgkg16fsS4pgg',
  'song_name': 'Make Them Pay',
  'duration_ms': 301950,
  'url': 'https://open.spotify.com/track/57rkFdhoKjgkg16fsS4pgg',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4'},
 {'song_id': '5ViLKrbyL3HD6wsq3AB9eI',
  'song_name': 'White Keys',
  'duration_ms': 144101,
  'url': 'https://open.spotify.com/track/5ViLKrbyL3HD6wsq3AB9eI',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '0PRccyeXfXZBxi8dkIv17c',
  'artist_id': '6USv9qhCn6zfxlBQIYJ9qs'},
 {'song_id': '1CPZ5BxNNd0n0nF4Orb9JS',
  'song_name': 'Golden',
  'duration_ms': 194607,
  'url': 'https://open.spotify.com/track/1CPZ5BxNNd0n0nF4Orb9JS',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '14JkAa6IiFaOh5s0nMyMU9',
  'artist_id': '7mW7Tv7NvywKKXqafZo0Lc'},
 {'song_id': '2lTm559tuIvatlT1u0JYG2',
  'song_name': 'BAILE INoLVIDABLE',
  'duration_ms': 367725,
  'url': 'https://open.spotify.com/track/2lTm559tuIvatlT1u0JYG2',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '5K79FLRUCSysQnVESLcTdb',
  'artist_id': '4q3ewBCX7sLwd24euuV69X'},
 {'song_id': '21IYMdzTrzSe191Cy5eMap',
  'song_name': 'Sailor Song',
  'duration_ms': 211978,
  'url': 'https://open.spotify.com/track/21IYMdzTrzSe191Cy5eMap',
  'popularity': None,
  'song_added': '2026-05-21T01:12:29Z',
  'album_id': '58vZavXqh1P5uoTXteudWl',
  'artist_id': '1iCnM8foFssWlPRLfAbIwo'}]

### Convert to DataFrame

In [19]:
album_df = pd.DataFrame.from_dict(album_list)
#drop duplicates
album_df = album_df.drop_duplicates(subset = ['album_id'])

In [20]:
artist_df = pd.DataFrame.from_dict(artist_list)
#drop duplicates
artist_df = artist_df.drop_duplicates(subset = ['artist_id'])

In [21]:
song_df = pd.DataFrame.from_dict(song_list)

In [22]:
#correct the datatype of 'release_date'
album_df['release_date'] = pd.to_datetime(album_df['release_date'], format='mixed')
album_df.info()

<class 'pandas.DataFrame'>
Index: 36 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      36 non-null     str
 1   name          36 non-null     str
 2   release_date  36 non-null     datetime64[us]
 3   total_tracks  36 non-null     int64
 4   url           36 non-null     str
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 1.7 KB

In [23]:
#correct the datatype of 'song_added'
song_df['song_added'] = pd.to_datetime(song_df['song_added'])
song_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      50 non-null     str
 1   song_name    50 non-null     str
 2   duration_ms  50 non-null     int64
 3   url          50 non-null     str
 4   popularity   0 non-null      object
 5   song_added   50 non-null     datetime64[us, UTC]
 6   album_id     50 non-null     str
 7   artist_id    50 non-null     str
dtypes: datetime64[us, UTC](1), int64(1), object(1), str(5)
memory usage: 3.3+ KB

In [24]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,2ANVost0y2y52ema1E9xAZ,Thriller,1982-11-30,9,https://open.spotify.com/album/2ANVost0y2y52em...
1,5cxMa6oLINJzmZ8lF7wWQN,Believe,2012-01-01,13,https://open.spotify.com/album/5cxMa6oLINJzmZ8...
2,3ukkRHDHbN8tNRPKsGZR1h,ARIRANG,2026-03-20,14,https://open.spotify.com/album/3ukkRHDHbN8tNRP...
3,0OAv7DCME2AV4q1KPO95HY,ICEMAN,2026-05-15,18,https://open.spotify.com/album/0OAv7DCME2AV4q1...
4,05jbNkYoEQdjVDHEHtg1gY,"Don't Forget About Me, Demos",2018-10-16,8,https://open.spotify.com/album/05jbNkYoEQdjVDH...

In [25]:
artist_df.head()

,artist_id,artist_name,external_url
0,3fMbdgg4jU18AjLCKBhRSm,Michael Jackson,https://api.spotify.com/v1/artists/3fMbdgg4jU1...
1,1uNFoZAHBGtllmzznpCI3s,Justin Bieber,https://api.spotify.com/v1/artists/1uNFoZAHBGt...
2,0hCNtLu0JehylgoiP8L4Gh,Nicki Minaj,https://api.spotify.com/v1/artists/0hCNtLu0Jeh...
3,3Nrfpe0tUJi4K4DXYWgMUX,BTS,https://api.spotify.com/v1/artists/3Nrfpe0tUJi...
4,3TVXtAsR1Inumwj472S9r4,Drake,https://api.spotify.com/v1/artists/3TVXtAsR1In...

In [26]:
song_df.head()

,song_id,song_name,duration_ms,url,popularity,song_added,album_id,artist_id
0,7J1uxwnxfQLu4APicE5Rnj,Billie Jean,293802,https://open.spotify.com/track/7J1uxwnxfQLu4AP...,None,2026-05-21 00:32:20+00:00,2ANVost0y2y52ema1E9xAZ,3fMbdgg4jU18AjLCKBhRSm
1,6QFCMUUq1T2Vf5sFUXcuQ7,Beauty And A Beat,227986,https://open.spotify.com/track/6QFCMUUq1T2Vf5s...,None,2026-05-21 00:32:55+00:00,5cxMa6oLINJzmZ8lF7wWQN,1uNFoZAHBGtllmzznpCI3s
2,68lbSrXDORS51pmyjZv712,SWIM,159007,https://open.spotify.com/track/68lbSrXDORS51pm...,None,2026-05-21 00:32:58+00:00,3ukkRHDHbN8tNRPKsGZR1h,3Nrfpe0tUJi4K4DXYWgMUX
3,514joG57v4yKTsfQmz7stz,Janice STFU,237344,https://open.spotify.com/track/514joG57v4yKTsf...,None,2026-05-21 00:33:03+00:00,0OAv7DCME2AV4q1KPO95HY,3TVXtAsR1Inumwj472S9r4
4,7yNf9YjeO5JXUE3JEBgnYc,Babydoll,97960,https://open.spotify.com/track/7yNf9YjeO5JXUE3...,None,2026-05-21 00:33:12+00:00,05jbNkYoEQdjVDHEHtg1gY,6USv9qhCn6zfxlBQIYJ9qs